#!/usr/bin/perl -w

use strict;

use Getopt::Long;
use AppConfig;

my $debug = 0;

if ( @ARGV != 2 ) {
  print "Usage:\n\tpost_pxe_delivery_passed <mac> <ip>\n";
  exit 1;
}

# get the sysconfig option settings
my $sysconfigfile = '/etc/sysconfig/baracus';
my $sysconfig = AppConfig->new( {CREATE => 1} );
$sysconfig->define( 'baracus_options=s',
                    'autodisablepxe=s',
                   );
$sysconfig->file( $sysconfigfile );
my $baracus_options = $sysconfig->get( 'baracus_options' );
my $autodisablepxe  = $sysconfig->get( 'autodisablepxe'  );

$debug = 1 if ( defined $baracus_options and $baracus_options =~ m|debug| );

unless ( defined $autodisablepxe and $autodisablepxe eq "yes" ) {
    print "post_pxe_deliver_passed called but autodisablepxe flag != 'yes'\n"
        if $debug;
    exit 0;
}

my $mac = shift;
my $ip  = shift;

my $pxename = $mac;
$pxename =~ s|:|-|g;
$pxename = "01-" . $pxename;

my $description = "delivered and auto-disabled";

print "baconfig update tftp --name $pxename --noenable --description \"$description\"" if $debug;

my $status = system("baconfig update tftp --name $pxename --noenable --description \"$description\"");

exit $status;

die "does not execute";
