#!/bin/bash

echo "[`date +"%a %b %d %H:%M:%S %Y"`] $0 $*" >> ~baracus/logs/baracusd 2>&1

host=$1
ip=$2

# uuid=$3
# mac=$4 - maybe

ssh root@gfs1.lsg.lab.novell.com /etc/nagios/objects/prod/add_hosts $host $ip
#ssh root@blade9.lsg.lab.novell.com /etc/nagios/objects/prod/add_hosts $host $ip
