#!/usr/bin/perl

use CGI qw(:standard);

$query = new CGI;

my $result = "\n\n\n\n";
my $command;

my @names = $query->param;

$command = "sudo create_install_host add ";
foreach( @names)
{
	$myname = $_;
	$myval = param($_);
	
	if( $myname eq "profile")
	{
		@split = split( "=", "$myval", 2);
		$myval = @split[1];
	}
	
	$p = " --".$myname."=".$myval;
	$command = $command.$p;
}

$result = $result.`$command 2>&1`;
chomp $result;

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/css/forms.css' type='text/css' >
	</head>
	<body>
	<div id='output'>
	<textarea>$result</textarea>
	<h1>Create Install Host</h1>
	<form action="/perl/create"><input type="submit" name="back" value="<< Back"></form> 
	</div>

	<body>
</html>

HTML0

;
