#!/usr/bin/perl

# use module

use CGI qw(:standard);

$p1 = param('sample') || '<i>(No input)</i>';

print <<END;
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<title>LSG - Response</title>
<h1>LSG - Response</h1>
<p>You typed: $p1</p>
END
;
