#!/usr/bin/perl -w

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use strict;
use CGI;

my $query = new CGI;
my $distro = $query->param('distro');
my $data = getData( $distro);

print $query->header;
print $data; 

sub getData
{
	my $distro = shift @_;
	my $r = "";
	my @addonLine = ();
	$r = $r."<h1>AddOns:</h1><h4>(hold ctrl for multiple)</h4><br>\n";
	$r = $r."<select name='addon' multiple size='4' onClick='addonUpdate()'>\n";	
	foreach( BAdb::getAddonsForDistro( $distro, "", "ready"))
	{
		@addonLine = split( " ", $_);
		$r = $r."<option value='$addonLine[0]'>$addonLine[0]</option>";
	}
	$r = $r."</select>\n";
	return $r;
}

