#!/usr/bin/perl -w
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use strict;
use CGI;

my $query = new CGI;
my $distro = $query->param('distro');
my $data = getData( $distro);

print $query->header;
print $data; 

sub getData
{
	my $distro = shift @_;
	my $r = "";
	my @addonLine = ();
	$r = $r."<h1>AddOns:</h1><h4>(hold ctrl for multiple)</h4><br>\n";
	$r = $r."<select name='addon' multiple size='4' onClick='addonUpdate()'>\n";	
	foreach( BAdb::getAddonsForDistro( $distro, "", "ready"))
	{
		@addonLine = split( " ", $_);
		$r = $r."<option value='@addonLine[0]'>@addonLine[0]</option>";
	}
	$r = $r."</select>\n";
	return $r;
}

