#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
	
my $content = getContent();
		 
print "Content-type: text/html\n\n";

print <<HTML;

<html>

<head>
	<link rel='stylesheet' href='/$BATools::baRoot/css/about.css' type='text/css' >
</head>

<body bgcolor="gainsboro" >
<div id="data">
<pre>$content</pre>
</div>
</body>
</html>

HTML
;

sub getContent
{
	my $r = `bapower man`;
	return $r;
}
