#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
	
my $content = getContent();
		 
print "Content-type: text/html\n\n";

print <<HTML;

<html>

<head>
	<link rel='stylesheet' href='/$BATools::baRoot/css/about.css' type='text/css' >
</head>
<body>
<pre>$content</pre>
</body>
</html>

HTML
;

# <body background="/baracus/images/bg-grad.jpg">

sub getContent
{
	my $r = `baconfig man`;
	return $r;
}
