#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use BAdb qw(:standard);
use CGI qw(:standard);

print "Content-type: text/html\n\n";


our $host = param('host');
our $mac = param('mac');
our $status = "status";

###########################################################################
#  Print HTML 
###########################################################################

print <<HTML0;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/baracus/script/ajax.js"></script>
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body>

	<div id='f-labels'>
	<form method="get" name="createAdd" action="/$BATools::baCGI/actionHandler">
	<div id='blockY'>
		<h1>Hostname:</h1>
		<br><input class="text" type="text" size="25" maxlength="15" name="host" value="$host" $dhost>
		<br>
		<h1>MAC Address:</h1><br><input class="text" type="text" size="25" name="mac" value="$mac" $macD onkeypress="return mac_only(event)">
		<br>
	</div>

	<div id='blockZ'>
		<input type="submit" value="Resume" name="noRescue" width="300">
		<input class="clear" type="button" value="Clear" onClick="location.href='/baracus/ba/actionNoRescue'">
        <input type=hidden name="rurl" value="actionNoRescue">
        <input type=hidden name="sub" value="noRescue" >
	</div>

	</form>
	</div>
</body>
</html>
HTML0

sub debugPrint
{
	if( $BATools::debug)
	{
		push( @errors, $_[0]);
	}
}
