#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

my $op = param('op') || "Build";
my $current = "";

my @tmenu = ( "Build", "Rescue", "NoRescue", "LocalBoot", "NetBoot", "DiskWipe");
my @tlink = ( "actionBuild", "actionRescue", "actionNoRescue", "actionLocal", "actionNet", "actionWipe");

my $tabs = BATools::getTabs( \@tmenu, \@tlink, $op, "action");

print "Content-type: text/html\n\n";

print <<HTML;

<html>
<head>
	<link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >
</head>
<body>
<br>
<br>
$tabs
</body>
</html>

HTML
;


