#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $query = new CGI;

my $result = "\n\n\n\n";
my $command;

my $sub = param('sub') || "";
my @names = $query->param;
my @params = ("mac", "ip", "hostname", "distro", "hardware", "module", "profile", "addon", "autobuild" );
my @vars = ( "netmask", "gateway", "dnsdomain", "dns1");
my $varlist;
my $redir = ' 2>&1';

my $command = "sudo bado build ";
my $header = "Do Build";

# override the command if we're really doing rescue
if ( $sub eq "rescue" ) {
    $command = "sudo bado rescue ";
    $header = "Do Rescue";
}

foreach $myname ( @names)
{
	@myvals = param($myname);
	
	if( BATools::isInArray( $myname, @params))
	{
		foreach $val( @myvals)
		{
			if( $val)
			{
				$p = " --".$myname."=".$val;	
				$command = $command.$p;
			}
		}
	}
	elsif( BATools::isInArray( $myname, @vars))
	{
		foreach $val( @myvals)
		{
			if( $val)
			{
				$p = " ".$myname."=".$val;	
				$varlist = $varlist.$p;
			}
		}
	}
}

if( $varlist)
{
	$command = $command . qq| --vars "$varlist"|;
}
$command = $command." $redir";
$result = $result.`$command`;
$result = $result."\n\nCommand: $command\n\n\n\n";
chomp $result;

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
	</head>
	<body background="/baracus/images/bg-grad.jpg">
	<div id='output'>
	<pre>$result</pre>
	<h1>$header</h1>
	</div>

	<body>
</html>

HTML0
;
