#!/usr/bin/perl

use CGI qw( :standard );

use lib '/var/spool/baracus/www/modules';
use BATools qw( :standard );

my $blank = "New";

my $name     = param('name')    || "$blank";
my $nname    = param('nname')   || "";
my $filter   = param('filter')  || "";

our $version  = param('ver') || -1;
our $status   = param('sta') || -1;

my $items    = &getItems( $filter );
my $versions = &getVersions( $name, $filter );
my $content  = &getContent( $name, $version );

#my $statsel  = getStatus( $name, $filter, $status);

my $addupButtonValue = "";

$nname_placeholder = "undefined";

if( $name eq $blank)
{
	$addupButtonValue = "Add";
    $nname            = $nname_placeholder;
    $version          = -1;
    $status           = -1;
} else {
	$addupButtonValue = "Update";
    $nname            = $name;
}

print "Content-type: text/html\n\n";

print <<HTML0

<html>
  <head>
    <link type='text/css' rel='stylesheet' href='/$BATools::baRoot/css/config.css'>
    <script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
  </head>
  <body
     onLoad='selectThis(document.form1.profile, "$name");
       document.form1.profile.focus();
       document.form1.filter.value = "$filter";
       document.form1.nname.disabled   = ("$name" == "$blank") ? false : true;
       document.form1.submitt.disabled = ("$name" == "$blank") ? true  : false;
       document.form1.submitd.disabled = ("$name" == "$blank") ? true  : false; '>

     <form name='form1' action="configHandler" method="GET">

      <div id='config'>

        <div id='history'>Profile</div>

        <div id='textEdit'>

          <font class='name'>Name</font><br>

		  <img class='search'
               src='/$BATools::baRoot/images/searchI.gif'
               onClick='configReload( "", document.form1.filter.value, -1 );'/>
          <img class='sweep'
               src='/$BATools::baRoot/images/sweepI.gif'
               onClick='configReload( document.form1.profile.value, "", document.form1.ver.value );'/>
          <input type='text' class='filter' name='filter' value='$filterVal' onKeyPress='return configRemoveEnterKey(event, "", document.form1.filter.value, -1 );'>

          $items

          <font class='version'>Version</font><br>
          $versions

          <input class='submitt'
                 type='submit'
                 name='submitt'
                 value='Toggle Status'
                 onClick='document.form1.data.value = "";'
                 disabled />

          <input class='submitd'
                 type='submit'
                 name='submitd'
                 value='Delete'
                 onClick='document.form1.data.value = ""; return verifyDelete( document.form1.profile.value + " (version " + document.form1.profile.ver.value + ")");'
                 disabled />

          <input class='nname'
                 type='text'
                 name='nname'
                 value="$nname"
                 onFocus='this.form.nname.value="";'
                 disabled />

		  <input class='submit'
                 type='submit'
                 name='submitau'
                 value='$addupButtonValue'
                 onClick='if ( "$addupButtonValue" == "Add" )
                          {
                            return verify( document.form1.nname, "You must enter a name for this profile");
                          } else
                          {
                            return verify( document.form1.profile, "You must select an entry to Update");
                          }' />


          <font class='data'>Settings</font>
          <textarea name='data'>$content</textarea>
        </div>

        <input type='hidden' name='op' value='profile'>

      </div>
    </form>
  </body>
</html>
HTML0
;

sub getItems
{
    my $filter = shift;
	my $r = "";

	$r .= qq|<select class='name' name='profile' size='6' onClick='configReload(this.value, "$filter", -1)'>\n|;
	$r .= "<option value='$blank'>$blank</option>\n";
	foreach( BAdb::getProfileListAll( $filter ) ) {
		$r .= "<option value='$_'>$_</option>\n";
	}
	$r .= "</select>";
	return $r;
}

sub getVersions
{
	my $name = shift;
	my $filter = shift;

	my $r = "";
	my $selected = "";
	my $count = 0;

	$r .= qq|<select class='version' size='5' onClick='configReload( "$name", "$filter", this.value)'>\n|;

	if( $name ne "" and $name ne $blank ) {
		foreach( BAdb::getProfileVersionList( $name, "yes")) {
			my ($xVer,$xSta) = split( "/", $_);

			$statString = $xSta eq 0 ? "disabled" : "enabled" ;
			if( $version eq -1 && $count eq 0)
			{
				$selected = "selected";
				$version = $xVer;
                $status = $xSta;
			}
			elsif( $version ne -1 and $version eq $xVer)
			{
				$selected = "selected";
                $status = $xSta;
			}
			else
			{
				$selected = "";
			}
			$r .= "<option $selected value='$xVer'>version $xVer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( $statString )</option>\n";
			++ $count;
		}
	}
	$r .= "</select>\n";
	$r .= "<input type='hidden' name='ver' value='$version'>\n";
	$r .= "<input type='hidden' name='sta' value='$status'>\n";

	return $r;
}

sub getContent
{
    my $name = shift;
    my $version = shift;

    my $r;
    unless ( $name eq "" or $name eq $blank ) {
        $r = BAdb::getProfile( $name, $version, "no" );
    }
    return $r;
}
