#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $pName = param('pname') || "";
my $nName = param('nname') || "";
our $ver = param('ver') || -1;
our $sta = param('sta') || -1;

my $versions = getVersions( $pName);
my $profiles = getProfiles();
my $template = getTemplate( $pName);

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/config.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body background="/baracus/images/bg06.jpg" onLoad='selectThis(document.form1.profile, "$pName")'>
		<form action="/baracus/ba/configHandler" name='form1'>
		<div id='config'>
		<div id='history'>Profile Delete</div>
		
		<div id='textEdit'>
		<font class='profile'>Profile</font>
		$profiles
		<font class='version'>Version</font>
		$versions
		<br><br>
		<font class='data'>Profile Data</font>
		<textarea name='pData' disabled>$template</textarea>
		</div>
		<input class='submit' type='submit' name='submit' value='Delete' onClick='return verifyDelete( this.form.profile.value + " (version " + this.form.versions.value + ")")'/>
		<input type='hidden' name='op' value='prof'>
		<input type='hidden' name='sub' value='del'>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getProfiles
{
	my $r = "";
	$r = $r."<select class='profile' name='profile' size='5' onClick='profReload(this.value, \"\", -1)'>";
	
	my @profiles = BAdb::getProfileListAllFromDB();
	#$r = $r."\n<option value=''>PLEASE SELECT</option>\n";
	foreach( @profiles)
	{
		$r = $r."<option value='$_'>$_</option>\n";	
	}
	
	$r = $r."</select>";
	
	return $r;
}

sub getTemplate
{
	my $prof = $_[0];
	if( $prof eq "")
	{
		$r = "";
	}
	else
	{
		$r = BAdb::getProfileFromDB( $prof, $ver, "yes");
	}
	return $r;
}

sub getVersions
{
	my($pName) = @_;
	my $r = "";
	my $selected = "";
	my $count = 0;
	my @verSplit;
	
	$r = $r."<select class='version' name='versions' size='5' onClick='profReload( \"$pName\", \"\", this.value)'>\n";

	if( $pName ne "")
	{
		my @vList = BAdb::getPofileVersionList( $pName, "yes");
		foreach( @vList)
		{
			@verSplit = split( "/", $_);
			$xVer = @verSplit[0];
			$xSta = @verSplit[1];
			$status = $xSta eq  1 ? "enabled" : "disabled";
			if( $ver eq -1 && $count eq 0)
			{
				$selected = "selected";
				$ver = $xVer;
				$sta = $xSta;
			}
			elsif( $ver ne -1 && $ver eq $xVer)
			{
				$selected = "selected";
				$sta = $xSta;
			}
			else
			{
				$selected = "";
			}
	
			$r = $r."<option $selected value='$xVer'>version $xVer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( $status )</option>\n";
			++ $count;
		}
	}
	
	$r = $r."</select>\n";
	$r = $r."<input type='hidden' name='ver' value='$ver'>\n";
	$r = $r."<input type='hidden' name='sta' value='$sta'>\n";

	return $r;
}

sub getVersions2
{
	my($pName) = @_;
	my $r = "";
	my $selected = "";
	my $count = 0;

	$r = $r."<select class='version' name='versions' size='5' onClick='profReload( \"$pName\", \"\", this.value)'>\n";

	if( $pName ne "")
	{
		my @vList = BAdb::getPofileVersionList( $pName, "no");
		foreach( @vList)
		{
			if( $ver eq -1 && $count eq 0)
			{
				$selected = "selected";
				$ver = $_;
			}
			elsif( $ver ne -1 && $ver eq $_)
			{
				$selected = "selected";
			}
			else
			{
				$selected = "";
			}
	
			$r = $r."<option $selected value='$_'>version $_</option>\n";
			++ $count;
		}
	}
	
	$r = $r."</select>\n";
	$r = $r."<input type='hidden' name='ver' value='$ver'>\n";

	return $r;
}

