#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

my $op = param('op') || "Distribution";
my $current = "";

my @tmenu = ( "Distribution", "Hardware", "Module", "Profile");
my @tlink = ( "configDist", "configHW", "configMod", "configProf");		

my $tabs = BATools::getTabs( \@tmenu, \@tlink, $op, "config");
		 
print "Content-type: text/html\n\n";

print <<HTML;

<html>
<head>
	<link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >
</head>
<body>
<br>
<br>
$tabs
</body>
</html>

HTML
;


