#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $Name = param('name') || "";

my $items = getItems();
my $content = getContent( $Name);

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/config.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body onLoad='selectThis(document.form1.item, "$Name")'>
		<form name='form1'>
		<div id='config'>
		<div id='history'>Hardware List</div>
		<div id='textEdit'>
		<font class='name'>Hardware</font>
		$items
		<br><br>
		<font class='data'>Hardware Data</font>
		<textarea name='data' readonly>$content</textarea>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $r = "";
	$r = $r."<select class='name' name='item' size='5' onClick='confReload(this.value, \"\", -1)'>";
	
	my @hardware = BAdb::getHardwareList();
	foreach( @hardware)
	{
		$r = $r."<option value='$_'>$_</option>\n";	
	}
	
	$r = $r."</select>";
	
	return $r;
}

sub getContent
{
	my $name = $_[0];
	if( $name eq "")
	{
		$r = "";
	}
	else
	{
		$r = BAdb::getHardware( $name);
	}
	return $r;
}
