#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $Name = param('name') || "";
our $nName = param('nname') || "";
our $ver = param('ver') || -1;

my $versions = getVersions( $Name);
my $items = getItems();
my $template = getTemplate( $Name);
my $distros = getDistros();

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/config.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
		<script type="text/javascript" src="/$BATools::baRoot/script/lists.js"></script>
		<style type="text/css">
			#cols div{position:absolute;top:200;border:0px solid white;}
			#cols font{margin-left:5px;}
			#cols select{width:150;margin-left:5px;color:#6DB33F;}
			#colCert{left:0;width:160;}
			#colDistro{left:215;width:160;}
			#colMand{left:430;width:160;}
			#colButtonL{left:162;width:50}
			#colButtonR{left:377;width:50}
			#colButtonL input{align:center;width:50px;color:white;font-weight:bold}
			#colButtonR input{align:center;width:50px;color:white;font-weight:bold}
		</style>
		<script language="javascript" type="text/javascript">
			/*
				To use columnEventHandler we need to implement these functions to 
				identify the three columns and relavent buttons.  
			*/ 
			function getCenter(){return document.form1.distro;}
			function getLeft(){return document.form1.optional;}
			function getRight(){return document.form1.mand;}			
			function cTOl(){return document.form1.cTOl;}			
			function cTOr(){return document.form1.cTOr;}			
			function lTOc(){return document.form1.lTOc;}			
			function rTOc(){return document.form1.rTOc;}	
			function localVerify(){
				cert =  getLeftList(",");
				mancert = getRightList(",");
				if( mancert != "") {
					if( cert != "")	{
						cert = cert + ",";
					}
					cert = cert + mancert;
				}
				document.form1.mancert.value = mancert;
				document.form1.cert.value = cert;

				return verify( document.form1.nname, "You must enter a Module Name");
			}		
		</script>
	</head>
	<body onLoad='selectThis(document.form1.module, "$Name");initCols()'>
		<form action="/baracus/ba/configHandler" name='form1'>
		<div id='config'>
		<div id='history' style="color:black">Module Add</div>
		<div id='textEdit'>
		
		<font class='name'>Template</font>
		$items
		<font class='version'>Version</font>
		$versions
		<br><br>
		<font class='dataShort'>Module Data</font>
		<textarea class='short' name='data'>$template</textarea>
		<font class='nname'>Module Name</font>
		<input class='nname' type='text' name='nname' value="$nName"\>
			<div id='cols'>
				<div id='colCert'>
                	<font class='basic'>Certified Optional</font>
					<select name='optional' size=5 onClick='colSelectHandler(this.name)'>
					</select>
				</div>
				<div id='colButtonL'>
					<br>
					<input type='button' disabled name='cTOl' value='<<' onClick='colEventHandler(this.name)'>
					<input  type='button' disabled name='lTOc' value='>>' onClick='colEventHandler(this.name)'>
				</div>
				<div id='colDistro'>
                	<font class='basic'>Available Distros:</font>
					$distros
				</div>
				<div id='colButtonR'>
					<br>
					<input  type='button' disabled name='cTOr' value='>>' onClick='colEventHandler(this.name)'>
					<input  type='button' disabled name='rTOc' value='<<' onClick='colEventHandler(this.name)'>
				</div>
				<div id='colMand'>
                	<font class='basic'>Certified Mandatory</font>
					<select name='mand' size=5 onClick='colSelectHandler(this.name)'>
					</select>
				</div>
			</div>
		</div>
		<input class='submit' type='submit' name='submit' value='Add' onClick='return localVerify()'/>
		<input type='hidden' name='op' value='mod'>
		<input type='hidden' name='sub' value='add'>

		<input type='hidden' name='cert' value=''>
		<input type='hidden' name='mancert' value=''>
		
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $r = "";
	$r = $r."<select class='name' name='module' size='5' onClick='confReload(this.value, this.form.nname.value, -1)'>";
	
	my @profiles = BAdb::getModuleListAll();
	$r = $r."\n<option value=''>BLANK</option>\n";
	foreach( @profiles)
	{
		$r = $r."<option value='$_'>$_</option>\n";	
	}
	
	$r = $r."</select>";
	
	return $r;
}

sub getDistros()
{
	my $r = "";

	$r = $r.BATools::getDistroSelectionList( "", "", "size=5 onClick='colSelectHandler(this.name)'", "*");
	
	return $r;
}

sub getTemplate
{
	my $mod = $_[0];
	if( $mod eq "")
	{
		$r = "";
	}
	else
	{
		$r = BAdb::getModule( $mod, $ver, "no");
	}
	return $r;
}

sub getVersions
{
	my($Name) = @_;
	my $r = "";
	my $selected = "";
	my $count = 0;
	my @verSplit;
	
	$r = $r."<select class='version' size='5' onClick='confReload( \"$Name\", \"\", this.value)'>\n";

	if( $Name ne "")
	{
		my @vList = BAdb::getModuleVersionList( $Name, "yes");
		foreach( @vList)
		{
			@verSplit = split( "/", $_);
			$xVer = @verSplit[0];
			$xSta = @verSplit[1];
			$status = $xSta eq  1 ? "enabled" : "disabled";
			if( $ver eq -1 && $count eq 0)
			{
				$selected = "selected";
				$ver = $xVer;
				$sta = $xSta;
			}
			elsif( $ver ne -1 && $ver eq $xVer)
			{
				$selected = "selected";
				$sta = $xSta;
			}
			else
			{
				$selected = "";
			}
	
			$r = $r."<option $selected value='$xVer'>version $xVer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( $status )</option>\n";
			++ $count;
		}
	}
	
	$r = $r."</select>\n";
	$r = $r."<input type='hidden' name='ver' value='$ver'>\n";
	$r = $r."<input type='hidden' name='sta' value='$sta'>\n";

	return $r;
}

