#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
	
my $content = getContent();
		 
print "Content-type: text/html\n\n";

print <<HTML;

<html>

<head>
	<link rel='stylesheet' href='/$BATools::baRoot/css/tabs.css' type='text/css' >
</head>

<body background="/baracus/images/bg-grad.jpg">
<pre class="content">$content</pre>
</body>
</html>

HTML
;

sub getContent
{
	my $r = "Module Configuration";
	return $r;
}
