#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $redir = ' 2>&1';
my $dist = getContent();

my $ccurl = "";

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body background="/baracus/images/bg06.jpg">
		<div id='f-labels'>
		<div id='history'>Distribution List</div>
		<div id='block1'>
		<br><br><h3>&nbsp;Please select for more information.</h3>
		</div>
		<div id='block2'>
		$dist
		</div>
		<div id='status'>
		<iframe src=\"$ccurl\" scrolling='no' height='100%' width='100%' frameborder='0' id='infoBox' ></iframe>
		</div>
		</div>
	</body>
</html>

HTML0
;

sub getContent
{
	my $r = "";
	$r = $r."<form name='createAdd'>\n";
	$r = $r.BATools::getDistroSelectionList( "0", "", "size='25' onClick='distUpdate()'");
	$r = $r."</form>\n";
	
	return $r;
}