#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

my $op = param('op') || "Hardware";
my $sub = param('sub') || "";
my $current = "";

my @tmenu = ( 	"Hardware",
				"Module/list/status/update/add/delete",
				"Profile/list/status/update/add/delete");
				
my @tlink = ( 	"configHW",
				"configMod/configMod/configModS/configModU/configModA/configModD",
				"configProf/configProf/configProfS/configProfU/configProfA/configProfD");		

my $tabs = BATools::getTabs( \@tmenu, \@tlink, $op, $sub, "config");
		 
print header();

print <<HTML;
<html>
<head>
	<link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >
</head>
<body>
<br>
<br>
$tabs
</body>
</html>

HTML
;


