#!/usr/bin/perl

use strict;
use warnings;

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);

use CGI qw(:standard);

my $op = param('op') || "Profile";
my $sub = param('sub') || "";
my $current = "";

my @tmenu =
    (
     "Profile",
     "Hardware",
     "Autobuild",
     "Module",
     );

my @tlink =
    (
     "configProfile",
     "configHardware",
     "configAutobuild",
     "configModule",
     );

my $tabs = BATools::getTabs( \@tmenu, \@tlink, $op, $sub, "/baracus/ba/config");

print header();

print <<HTML;
<html>
  <head>
	<link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >
  </head>
  <body>
    <br>
    <br>
    $tabs
  </body>
</html>

HTML
;
