#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $Name = param('name') || "";
my $nName = param('nname') || "";
our $ver = param('ver') || -1;
our $sta = param('sta') || -1;

my $versions = getVersions( $Name);
my $items = getItems();
my $template = getTemplate( $Name);

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/config.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body onLoad='selectThis(document.form1.module, "$Name")'>
		<form action="/baracus/ba/configHandler" name='form1'>
		<div id='config'>
		<div id='history'>Module Delete</div>
		
		<div id='textEdit'>
		<font class='name'>Module</font>
		$items
		<font class='version'>Version</font>
		$versions
		<br><br>
		<font class='data'>Module Data</font>
		<textarea name='data' disabled>$template</textarea>
		</div>
		<input class='submit' type='submit' name='submit' value='Delete' onClick='return verifyDelete( this.form.items.value + " (version " + this.form.versions.value + ")")'/>
		<input type='hidden' name='op' value='mod'>
		<input type='hidden' name='sub' value='del'>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $r = "";
	$r = $r."<select class='name' name='module' size='5' onClick='confReload(this.value, \"\", -1)'>";
	
	my @modules = BAdb::getModuleListAll();
	#$r = $r."\n<option value=''>PLEASE SELECT</option>\n";
	foreach( @modules)
	{
		$r = $r."<option value='$_'>$_</option>\n";	
	}
	
	$r = $r."</select>";
	
	return $r;
}

sub getTemplate
{
	my $mod = $_[0];
	if( $mod eq "")
	{
		$r = "";
	}
	else
	{
		$r = BAdb::getModule( $mod, $ver, "yes");
	}
	return $r;
}

sub getVersions
{
	my($Name) = @_;
	my $r = "";
	my $selected = "";
	my $count = 0;
	my @verSplit;
	
	$r = $r."<select class='version' name='versions' size='5' onClick='confReload( \"$Name\", \"\", this.value)'>\n";

	if( $Name ne "")
	{
		my @vList = BAdb::getModuleVersionList( $Name, "yes");
		foreach( @vList)
		{
			@verSplit = split( "/", $_);
			$xVer = @verSplit[0];
			$xSta = @verSplit[1];
			$status = $xSta eq  1 ? "enabled" : "disabled";
			if( $ver eq -1 && $count eq 0)
			{
				$selected = "selected";
				$ver = $xVer;
				$sta = $xSta;
			}
			elsif( $ver ne -1 && $ver eq $xVer)
			{
				$selected = "selected";
				$sta = $xSta;
			}
			else
			{
				$selected = "";
			}
	
			$r = $r."<option $selected value='$xVer'>version $xVer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;( $status )</option>\n";
			++ $count;
		}
	}
	
	$r = $r."</select>\n";
	$r = $r."<input type='hidden' name='ver' value='$ver'>\n";
	$r = $r."<input type='hidden' name='sta' value='$sta'>\n";

	return $r;
}
