#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $query = new CGI;

my $result = "\n\n\n\n";
my $command;

my @names = $query->param;
my @params = ("mac", "ip", "hostname", "distro", "hardware", "module", "profile");
my @vars = ( "netmask", "gateway", "dnsdomain", "dns1");
my $varlist;

my $command = "sudo bahost add ";

foreach $myname ( @names)
{
	@myvals = param($myname);
	
	if( BATools::isInArray( $myname, @params))
	{
		foreach $val( @myvals)
		{
			if( $val)
			{
				$p = " --".$myname."=".$val;	
				$command = $command.$p;
			}
		}
	}
	elsif( BATools::isInArray( $myname, @vars))
	{
		foreach $val( @myvals)
		{
			if( $val)
			{
				$p = " ".$myname."=".$val;	
				$varlist = $varlist.$p;
			}
		}
	}
}

if( $varlist)
{
	$command = $command." --vars $varlist";
}

$result = $result.`$command 2>&1`;
#$result = $result."\n\nCommand: $command\n\n\n\n";
chomp $result;

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
	</head>
	<body background="/baracus/images/bg-grad.jpg">
	<div id='output'>
	<pre>$result</pre>
	<h1>Create Install Host</h1>
	</div>

	<body>
</html>

HTML0
;
