#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $query = new CGI;

my $result = "\n\n\n\n";
my $command;

my @names = $query->param;
my @params = ("mac", "ip", "hostname", "distro", "hardware", "module", "profile", "addon");
my @vars = ( "netmask", "gateway", "dnsdomain", "dns1");
my $varlist;
my $redir = ' 2>&1';

my $command = "sudo bado build ";

foreach $myname ( @names)
{
	@myvals = param($myname);
	
	if( BATools::isInArray( $myname, @params))
	{
		foreach $val( @myvals)
		{
			if( $val)
			{
				$p = " --".$myname."=".$val;	
				$command = $command.$p;
			}
		}
	}
	elsif( BATools::isInArray( $myname, @vars))
	{
		foreach $val( @myvals)
		{
			if( $val)
			{
				$p = " ".$myname."=".$val;	
				$varlist = $varlist.$p;
			}
		}
	}
}

if( $varlist)
{
	$command = $command." --vars $varlist";
}
$command = $command." $redir";
$result = $result.`$command`;
#$result = $result."\n\nCommand: $command\n\n\n\n";
chomp $result;

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
	</head>
	<body background="/baracus/images/bg-grad.jpg">
	<div id='output'>
	<pre>$result</pre>
	<h1>Create Install Host</h1>
	</div>

	<body>
</html>

HTML0
;
