#!/usr/bin/perl


use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

my $cur = param('cur');

my $content = getContent($cur);

print "Content-type: text/html\n\n";

print <<HTML0;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body onload='scrollDown()'>
	<div id='inStatusW'>
	<textarea id="tscroll" name="comments" readonly="yes">$content</textarea>
	<input type='submit' class='refresh' value="Refresh Now" onClick='refresh(\"\")'> 
	</div>
	</body>
</html>

HTML0
;

sub getContent
{
	my $cFile = $_[0];
	my $r = "";
	$r = $r.BATools::readFile( $BATools::poolPath.$cFile, "Finished Processing");
	return $r;
}