#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $name = param('host') || "";
my $filter = param('filter') || "";

my $items = getItems( $name, $filter);
my $content;

if( $items =~ m/selected/)
{
	$content = getContent( $name);
}

print "Content-type: text/html\n\n";

print <<HTML0


<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/host.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body onLoad='selectThis(document.form1.host, "$name");document.form1.host.focus()'>
		<form method="POST" name='form1' action="/$BATools::baCGI/hostHandler">
		<div id='config'>
		<div id='history' style="color:black">Host Status</div>
		<div id='textEdit'>
		<img class='search' src='/$BATools::baRoot/images/searchI.gif' onClick='hostReload( document.form1.host.value, document.form1.filter.value)'/>
		<img class='sweep' src='/$BATools::baRoot/images/sweepI.gif' onClick='document.form1.filter.value="";hostReload( document.form1.host.value, document.form1.filter.value);'/>
		<input type='text' class='filter' name='filter' value='$filter' onKeyPress='return hostRemoveEnterKey(event)'>

		<input type="hidden" name="sub" value="sta">
		<input class="submit" name="submit" type="submit" value="Enable")'>
		<input class="submit" name="submit" type="submit" value="Disable")'>
		
		<font class='name'>Host Name</font><br>
		$items
		<br><br>
		<font class='dataShort'>Host Data</font>
		<textarea class='short' name='data' readonly>$content</textarea>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = $_[0];
	my $filter = $_[1];
	my $r = "";
	my $selected;
	
	$r = $r."<select class='nameWide' name='host' size='16' onChange='hostReload( document.form1.host.value, document.form1.filter.value)'>";
	
	my @items = BAdb::getHostTemplates( $filter);
	foreach( @items)
	{
		$selected = $_ eq $name ? "selected" : "";
		$r = $r."<option value='$_' $selected>$_</option>\n";	
	}
	
	$r = $r."</select>";
	
	return $r;	
}

sub getContent
{
	my $name = $_[0];
	if( $name eq "")
	{
		$r = "";
	}
	else
	{
		$r = BAdb::getHostTemplate( $name);
	}
	return $r;
}

