#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

print "Content-type: text/html\n\n";

my $sub = param('sub');				# subfunction
my $content = "";

my $headError = "<font class='error'>Error</font>";

if( $sub eq "del")
{
	$content = $content.delContent( param('host'));
	$header = delHeader();
}
else
{
	$content = $content."Invalid Subfunction: $sub";
	$header = $headError;
}

$content = $content."\n\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<div id='output'>
	<body background="/baracus/images/bg-grad.jpg" $refresh>
	<pre>$content</pre>
	<h1>$header</h1>
	<h3>$proc</h3>
	<body>
	</div>
</html>

HTML0

;
########################################################################################################
#  Subfunction = del (Delete Install Source)
########################################################################################################

sub delHeader()
{
	return "Delete Host Template";
}

sub delContent($)
{
	my $cmd = "sudo bahost remove --hostname $_[0]";
	my $r = `$cmd`;
	return $r;
}
