#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $redir = ' 2>&1';
my $command = "sudo baconfig list hardware --quiet $redir";
my $hardware = getContent( $command);

my $ccurl = "/$BATools::baCGI/createContent?caller=create&attr=hardware&val=default";

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body>
		<div id='f-labels'>
		<div id='block1'>
		<br><br><h3>&nbsp;Please select for more information.</h3>
		</div>
		<div id='block2'>
		$hardware
		</div>
		<div id='status'>
		<iframe src=\"$ccurl\" scrolling='no' height='100%' width='100%' frameborder='0' id='infoBox' ></iframe>
		</div>
		</div>
	</body>
</html>

HTML0
;

sub getContent
{
	my $command = $_[0];
	my $r = "";
	$r = $r."<form name='createAdd'>\n";
	$r = $r.BATools::getHardwareSelectionList( "", "", "size='25' onClick='hwUpdate()'");
	$r = $r."</form>\n";
	
	return $r;
}