#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

print "Content-type: text/html\n\n";

our $menuindex = 0;
our @menucmd;
our @menunames;

my $cmd;
my $data_file;
my $result;
my $request;
my $op;
my $data;
my $menuHTML;
my $randImage;
my $content;

$op = param('op') || '<i>(No input)</i>';
$data = param('data');

@menunames = ("Home",
			  "List Templates",
			  "List Hardware",
			  "Host Entries", 
			  "Source Entries",
			  "Processing",
			  "About");

@menucmd = ("home.html", 
		"/$BATools::baCGI/hostHandler?sub=temp.iframe", 
		"/$BATools::baCGI/hwHandler.iframe",
		"/$BATools::baCGI/create.iframe", 
		"/$BATools::baCGI/source.iframe",
		"/$BATools::baCGI/procHandler.iframe",
		"uc.html");

$menuHTML = createMenu( $op);
$randImage = getRandomImage();
$content = processCommand( $data);

########################################################################################################
#  Print HTML
########################################################################################################

print <<HTML1;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	
	<body bgcolor="white" onClick="parent_disable();">
	<div id="title">&nbsp;&nbsp;[ baracus ]</div> 
	<div id="subtitle">&nbsp;&nbsp;Linux Solutions Group</div> 
	<div id="line">	<hr size="10" align="left"></div>
	<div id="logo"><img src="/$BATools::baRoot/images/Geeko_icon3.jpg"\></div>
	<div id="nvlogo"><a href="http://www.novell.com"><img src="/$BATools::baRoot/images/nov_blk.gif"></a></div>

	<div id='mmenu'>
	<ul><br><br><br>
	$menuHTML
	</ul>
	</div>
	<div id='content'>
	$content
	</div>
	$randImage
	</body>
</html>

HTML1


########################################################################################################
#  Generate Menu From menunames / Highlight current selection
########################################################################################################

sub createMenu
{
	my $retString = "";
	my $divid = "";
	my $curop = $_[0];
	my $iter = 0;

	$menuindex = 0;
	
	foreach (@menunames)
	{
		if($_ eq $curop)
		{
			$divid = "cur";
			$menuindex = $iter;
		}
		
		$retString = $retString."\t<li><a href='/$BATools::baCGI/main?op=$_'><div id='$divid'>$_</div></a></li>\n";
		
		$divid = "";
		++ $iter;
	}

	return $retString;	
}	

########################################################################################################
#  Execute Command or include file if command ends with "html"
########################################################################################################

sub processCommand
{
	my $data = $_[0];
	my $retString = "";
	my $result;
	
	####################################################################################################
	#Menu Command maps to @menunames.
	#.html - puts html file inline (head and body tags should NOT be present in html file)
	#.iframe - strips .iframe from command and loads stripped command in iframe
	#All others are treated as executables - results displayed
	####################################################################################################

	$cmd = $menucmd[$menuindex];
	 
	if($data ne "")
	{
		$retString = $data;
	}
	elsif ($cmd =~ m/html\Z/)
	{
		$data_file="$BATools::baPath/htdocs/" . $cmd;
		open(DAT, $data_file) || print "Could not open file: " . $data_file;
		while(<DAT>)
		{
			$retString = $retString.$_;
		}
		close(DAT); 				
	}
	elsif ($cmd =~ m/iframe\Z/)
	{
		$cmd =~ s/.iframe//;
		$retString = "\t<iframe src='$cmd' width='650' height='850' scrolling='auto' frameborder='0' name='createframe' hspace=10 vspace=5 ></iframe>\n";
	}
	else
	{
		$result = `$cmd`;
		
		if ( $cmd !~ m/\Aperl/)
		{
			$result = "<ul>\n".$result;
			#Add <br> for each new line in $result
			$result=~s/\n/<br>\n\t<li>/g;
			$result = $result."</ul>\n";
		}
		
		$retString = "\t<div id='pcontent'>";
		$retString = $retString.$result;
		$retString = $retString."\t</div>\n";
	}
	
		return $retString;
}	

########################################################################################################
#  Get HTML for random image
########################################################################################################

sub getRandomImage()
{
					
		my @imgarray = ("150bball.png",
					 	"150mountaineer.png",
					 	"150samurai.png",
						"150snowboard.png",
						"150soccer.png",
						"150surfer.png");

	  	my $index = rand(6);
	  		
		return "\t<div id='geeko'><img src='/$BATools::baRoot/images/".@imgarray[$index]."'/></div>\n";
}
