#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use lib '/usr/share/baracus/perl/';
use BATools qw(:standard);
use BaracusConfig qw( :vars );
use CGI qw(:standard);

my $name = param('mac') || "";
my $filter = param('filter') || "";

my $items = getItems( $name, $filter );
my $content;

if( $items =~ m/selected/)
{
        $content = getContent( $name);
}

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
                <script type="text/javascript" src="/baracus/script/power.js"></script>
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <script type="text/javascript" src="/baracus/script/tablecloth.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
                <link rel='stylesheet' href='/$BATools::baRoot/css/tablecloth.css' type='text/css'>
		<link rel='stylesheet' href='/$BATools::baRoot/css/power.css' type='text/css'>
	</head>
                <form name='form1' action='powerHandler' target="">
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

                <form name='form1' action='powerHandler' target="">
		<div id='config'>
		<div id='histbar' style="color:black">Power</div>
		<div id='main'>
		<img class='search' src='/$BATools::baRoot/images/searchI.gif' onClick='document.form1.submit()'/>
		<img class='sweep' src='/$BATools::baRoot/images/sweepI.gif' onClick='document.form1.filter.value="";document.form1.submit()'/>
                <font class='filter'>Filter</font>
		<input type='text' class='filter' name='filter' value='$filter'>
                <input type='hidden' name='mac' value='test'>
                <font class='clink'><a href="http://$baVar{serverip}/baracus/ba/PowerCreate">Create Power Entry</a></font>
		<br><br>
                <div id='list'>
		$items
                </div>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = shift;
	my $filter = shift;
	my $r = "";
        my $linkR = "http://$baVar{serverip}/baracus/ba/powerRemove?mac=";

        if ( $filter eq "" ) { $filter = "%"; }

        $r = "<table class='list'>\n";
        $r .= "<tr>\n";
        $r .= "<th>Hostname</th>\n";
        $r .= "<th>MAC</th>\n";
        $r .= "<th>Type</th>\n";
        $r .= "<th colspan='4'></th>\n";
        $r .= "</tr>\n";

	my $hohref = BAdb::getPowerList( $filter );
	my $disabled;
	foreach  my $row ( keys %{$hohref} ) {
	    $r .= "<tr>\n";
            $r .= "<td width=\"215\">$hohref->{$row}->{'hostname'}</td>\n";
            $r .= "<td width=\"120\">$hohref->{$row}->{'mac'}<\/td>\n";
            $r .= "<td width=\"60\">$hohref->{$row}->{'ctype'}<\/td>\n";

	    $disabled = "disabled";
            $disabled = "" if ( $hohref->{$row}->{'ctype'} eq "virsh" );
 
            $r .= "<td width=\"40\"><input id=\"$hohref->{$row}->{'mac'}\" class='power' type=submit value='On' name='submit' onClick='popResponse(this.id)'><\/td>\n";
            $r .= "<td width=\"40\"><input id=\"$hohref->{$row}->{'mac'}\" class='power' type=submit value='Off' name='submit' onClick=\"popResponse(this.id)\"><\/td>\n";
            $r .= "<td width=\"50\"><input id=\"$hohref->{$row}->{'mac'}\" class='power' type=submit value='Status' name='submit' onClick=\"popResponse(this.id)\"><\/td>\n";
            $r .= "<td width=\"40\"><input id=\"$hohref->{$row}->{'mac'}\" class='power' type=submit value='VNC' $disabled name='submit2' onClick=\"setTarget('_blank')\"'><\/td>\n";
	    $r .= "<\/tr> \n";
	}	

	$r = $r."</table>\n";
	return $r;	
}

;
