#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use lib '/usr/share/baracus/perl/';
use BATools qw(:standard);
use BaracusConfig qw( :vars );
use CGI qw(:standard);

my $mac = "";
my $hostname = "";
my $bmcaddr = "";
my $type = "";
my $username = "";
my $passwd = "";

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
		<link rel='stylesheet' href='/$BATools::baRoot/css/power.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST" action="powerHandler">
		<div id='config'>
		<div id='histbar' style="color:black"><a href=\"http://$baVar{serverip}/baracus/ba/power\">Power<\/a> \ >  Create</div>
		<div id='main'>
                <font class='createname'>mac</font>
		<input type='text' class='createname' name='mac' value='$mac'>
                <font class='createip'>hostname</font>
                <input type='text' class='createip' name='hostname' value='$hostname'>
                <font class='createid'>BMC address</font>
                <input type='text' class='createid' name='bmcaddr' value='$bmcaddr'>
                <font class='createtype'>BMC Type</font>
                <select class='createtype' name='type'>
                   <option value='ipmi'>IPMI</option>
                   <option value='ilo'>ILO</option>
                   <option value='drac'>DRAC</option>
                   <option value='racs'>RACS</option>
                   <option value='bladecenter'>BLADECENTER</option>
                   <option value='apc'>APC</option>
                   <option value='virsh'>VIRSH</option>
                </select>
                <font class='createuser'>Username</font>
                <input type='text' class='createuser' name='username' value='$username'>
                <font class='createpasswd'>Password</font>
                <input type='text' class='createpasswd' name='passwd' value='$passwd'>
                <input type='submit' class='createentry' value='Add' name='submit'>
		<br><br>
                </div>
		</div>
                </div>
		</form>
	</body>
</html>
HTML0

;
