#!/usr/bin/perl


use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

my $cur = param( 'cur');
my $ref = param('ref') || "off";

chomp($cur);

my $content = getContent($cur);
my $refresh = getRefresh( $ref);
my $buttonName = getButtonName( $ref);

print "Content-type: text/html\n\n";

print <<HTML0;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body $refresh>
	<div id='inStatusW'>
	<textarea id="tscroll" name="comments" readonly="yes">$content</textarea>
	<input type="button" name="refresh" class="refresh" value="$buttonName" onClick='toggleRefresh()'> 
	</div>
	</body>
</html>

HTML0
;

sub getContent
{
	my $cFile = $_[0];
	my $r = "";
	$r = $r.BATools::readFile( $BATools::poolPath.$cFile, "\n\nFinished Processing");
	return $r;
}

sub getRefresh
{
	my $ref = $_[0];
	my $r = "";
	
	if( $ref eq "on")
	{
		$r = "onload='scrollDown()'";
	}
	return $r;
}

sub getButtonName
{
	my $ref = $_[0];
	my $r = "";
	if( $ref eq "on")
	{
		$r = "Turn Refresh Off";
	}
	else
	{
		$r = "Turn Refresh On";
	}
	return $r;
}
