#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $redir = ' 2>&1';
my $title = "Currently Processing";
my $current = getContent();

my $ccurl = "/baracus/blank.html";

print "Content-type: text/html\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body">
		<div id='f-labels'>
			<font class='history' style="color:black">Currently Processing</font>	
			<div id='blockW'>
			<form name='form1'>
			$current
			</form>
			<font class="select" style="color:black">Select from list for more info:</font>
			</div>

			<div id='statusW'>
			<iframe src=\"$ccurl\" scrolling='no' height='100%' width='100%' frameborder='0' id='infoBox' name='infoBox'></iframe>
			</div>

		</div>
	</body>
</html>

HTML0
;

sub getContent
{
	my $r = "";
	#$r = $r."<form name='createAdd'>\n";
	$r = $r.BATools::getCurrentProcSelectionList("", "enabled", "size=12 onChange='procChange()';");
	#$r = $r."</form>\n";
	
	return $r;
}
