#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

my $cur = param( 'cur');
my $ref = param('ref') || "off";

chomp($cur);

my $content = getContent($cur);
my $refresh = getRefresh( $ref);
my $buttonName = getButtonName( $ref);

print "Content-type: text/html\n\n";

print <<HTML0;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body $refresh>
	<div id='inStatusW'>
	<textarea id="tscroll" name="comments" readonly="yes">$content</textarea>
	<input type="button" name="refresh" class="refresh" value="$buttonName" onClick='toggleRefresh()'> 
	</div>
	</body>
</html>

HTML0
;

sub getContent
{
	my $cFile = $_[0];
	my $r = "";
	$r = $r.BATools::readFile( $BATools::poolPath.$cFile, "\n\nFinished Processing");
	return $r;
}

sub getRefresh
{
	my $ref = $_[0];
	my $r = "";
	
	if( $ref eq "on")
	{
		$r = "onload='scrollDown()'";
	}
	return $r;
}

sub getButtonName
{
	my $ref = $_[0];
	my $r = "";
	if( $ref eq "on")
	{
		$r = "Turn Refresh Off";
	}
	else
	{
		$r = "Turn Refresh On";
	}
	return $r;
}
