#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

our $rURL = "repo";
our $ref = "yes";
our $seconds = 3;
our $qStr = "";

my $refresh = "";


print "Content-type: text/html\n\n";

my $op   = param('op') || "";
my $repo = param('repo') || "";

my $content = "";

my $headError = "<font class='error'>Error</font>";

if ( $op eq "remove" ) {
    if ( $repo eq "" ) {
        $content = $content."Missing required data";
        $header = $headError;
    } else {
        $content = $content.RemoveRepoContent();
        $header = "Remove Repo";
    }
}
else {
    $content = $content."Routing error";
    $header = $headError;
}

if( $ref eq "yes")
{
	$refresh = "onLoad=\"doLoad( '$rURL', '$qStr', $seconds)\"";
}

$content = $content."\n\n\n";

print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<div id='output'>
	<body background="/baracus/images/bg-grad.jpg" $refresh>
	<pre>$content</pre>
	<h1>$header</h1>
	<h3>$proc</h3>
	<body>
	</div>
</html>

HTML0

;
########################################################################################################
# Add
########################################################################################################

sub RemoveRepoContent()
{
        my $cmd = "sudo barepo remove $repo ";

        my $r = $cmd . "\n";
        $r .= `$cmd`;
        return $r;
}
