#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $repo = param('repo') || "";

my $items = getItems( $repo );

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
                <script type="text/javascript" src="/baracus/script/tablecloth.js"></script>
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
                <link rel='stylesheet' href='/$BATools::baRoot/css/tablecloth.css' type='text/css'>
		<link rel='stylesheet' href='/$BATools::baRoot/css/repo.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST">
		<div id='config'>
		<div id='histbar' style="color:black"><a href=\"http://blade9/baracus/ba/repo\">Repository<\/a> \ >  $repo</div>
		<div id='main'>
                <font class='name'>RPM List</font>
		<br><br>
                <div id='repolist'>
		$items
                </div>
		</div>
                </div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = $_[0];
	my $r = "";
	my $selected;
        my $linkR = "http://blade9/baracus/ba/repoRemove?repo=test&rpm=";

	my @items;
        $r = "<table class='repolist'>\n";
	@items = BAdb::getRepoDetail( $repo );

	foreach( @items)
	{
            $r = $r."<tr>\n<td width=\"580\">$_<\/td>\n<td width=\"20\"><a href=\"$linkR$_\" style=\"text-decoration : none\">Remove<\/a><\/td>\n<\/tr> \n";
	}
	
	$r = $r."</table>\n";
	return $r;	
}

;
