#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $name = param('repo') || "";
my $filterVal = param('filter') || "";

my $items = getItems( $name, $filterVal );
my $content = getContent( $name );

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
                <script type="text/javascript" src="/baracus/script/tablecloth.js"></script>
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
                <link rel='stylesheet' href='/$BATools::baRoot/css/tablecloth.css' type='text/css'>
		<link rel='stylesheet' href='/$BATools::baRoot/css/repo.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST">
		<div id='config'>
		<div id='histbar' style="color:black">Repository</div>
		<div id='main'>
		<img class='search' src='/$BATools::baRoot/images/searchI.gif' onClick='document.form1.submit()'/>
		<img class='sweep' src='/$BATools::baRoot/images/sweepI.gif' onClick='document.form1.filter.value="";document.form1.submit()'/>
                <font class='filter'>Filter</font>
		<input type='text' class='filter' name='filter' value='$filterVal'>
                <font class='name'><a href="http://blade9/baracus/ba/repoCreate">Create Repo</a></font>
		<br><br>
                <div id='repolist'>
		$items
                </div>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = $_[0];
	my $filterVal = $_[1];
	my $r = "";
	my $selected;
        my $linkD = "http://blade9/baracus/ba/repoDetail?repo=";
        my $linkU = "http://blade9/baracus/ba/repoUpdate?repo=";

	my @items;
       # $r = $r."<select class='nameWide' name='repo' size='16' onChange='doSubmit( this)'>";
        $r = "<table class='repolist'>\n";
	@items = BAdb::getRepoList( $filterVal );

	foreach( @items)
	{
            $r = $r."<tr>\n<td width=\"495\">$_<\/td>\n<td width=\"20\"><a href=\"$linkD$_\" style=\"text-decoration : none\">Detail<\/a><\/td>\n<td width=\"20\"><a href=\"$linkU$_\" style=\"text-decoration : none\">Update<\/a><\/td>\n<\/tr> \n";
	}
	
	$r = $r."</table>\n";
	return $r;	
}

sub getContent
{
        my $name = shift @_;
        my $r;
        my @items;
	if( $name eq "")
	{
	    $r = "";
	}
	else
	{
            @items = BAdb::getRepoDetail( $name );
            foreach( @items ) {
                $r = $r."$_\n";
            }
	}
	return $r;
}

;
