#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $source_help = "$BATools::baPath/htdocs/help/source.hlp";

my $dselect = BATools::getDistroSelectionList();
my $help = print_help();

########################################################################################################
#  Print HTML
########################################################################################################

print "Content-type: text/html\n\n";

print <<HTML0;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body>
		<div id='f-labels'>
		<div id='block1'>
		<h1>List</h1><br><br>
		<h3>All Installation Sources</h3>
		<form action="/$BATools::baCGI/sourceHandler">
			<input type="hidden" name="sub" value="list">
			<input class="button" type="submit" value="List">
		</form>

	</div>

	<div id='block2'>
		<h1>Source Options</h1><br><br>
		<form name="add" action="/$BATools::baCGI/sourceHandler">
			<br>
			<!--
			<select name="subx">
			<option value="NONE" selected></option>
			<option value="add">Add</option>
			<option value="del">Delete</option>
			<option value="ena">Enable</option>
			<option value="dis">Disable</option>
			</select>
			-->
			<br>
			<h3>Distributions</h3>
			$dselect
			<br><h3>Operation</h3>
			<div id="radio">
			<input type="radio" name="sub" value="add"> Add<br>
			<input type="radio" name="sub" value="del"> Delete<br>
			<input type="radio" name="sub" value="ena"> Enable<br>
			<input type="radio" name="sub" value="dis"> Disable<br>
			<input type="radio" name="sub" value="ver"> Verify<br>
			</div>
			<input type="hidden" name="ref" value="yes">
			<input class="button" type="submit" value="Submit">
		</form>
	</div>

	<div id='debug'>
	<textarea name="comments" class="tbox" readonly="yes">$help</textarea>
	</div>
	</div>
	<body>
	</html>

HTML0

########################################################################################################
#  Read Help File
########################################################################################################

sub print_help()
{
	my $retString = "";
	open (MYFILE, $source_help) || return "Error Opening Help File:\n$!";
	while(<MYFILE>)
	{
		$retString = $retString.$_;
	}
	close (MYFILE);
	return $retString; 
}	

########################################################################################################
#  Print Source List for debug window
########################################################################################################

sub print_list()
{
	my $listcmd = "sudo /usr/share/baracus/perl/directSqlFS.pl list linux.sle";
	my $retString = "";
	
	open(CMD, "$listcmd 2>&1 |") || die "Failed: $!\n";
	
	while ( <CMD> )
	{
		$retString = $retString.$_;
	}
	return $retString;
}
