#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $source_help = "$BATools::baPath/htdocs/help/source.hlp";

my $dselect = BATools::getDistroSelectionList("", "", "size='22' onClick='distUpdate(document.ena.distro.value)'", "disabled");
my $help = print_help();

########################################################################################################
#  Print HTML
########################################################################################################

print "Content-type: text/html\n\n";

print <<HTML0;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body>
	<div id='f-labels'>
	<div id='block1'>
	<font class='history'>Enable Source Entries</font>
	</div>

	<div id='block2'>
		<form name="ena" action="/$BATools::baCGI/sourceHandler">
			<h3>Distributions</h3>
			$dselect
			<br>
			<input type="hidden" name="sub" value="ena">
			<input type="hidden" name="ref" value="yes">
			<input class="button" type="submit" value="Enable">
		</form>
	</div>

	<div id='status'>
	<iframe src=\"$ccurl\" scrolling='no' height='100%' width='100%' frameborder='0' id='infoBox' ></iframe>
	</div>
	</div>
	<body>
	</html>

HTML0

########################################################################################################
#  Read Help File
########################################################################################################

sub print_help()
{
	my $retString = "";
	open (MYFILE, $source_help) || return "Error Opening Help File:\n$!";
	while(<MYFILE>)
	{
		$retString = $retString.$_;
	}
	close (MYFILE);
	return $retString; 
}	

