#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $source_help = "$BATools::baPath/htdocs/help/source.hlp";

my $dselect = BATools::getDistroSelectionList("", "", "size='10'");
my $help = print_help();

########################################################################################################
#  Print HTML
########################################################################################################

print "Content-type: text/html\n\n";

print <<HTML0;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
	</head>
	<body background="/baracus/images/bg06b.jpg">
	<div id='f-labels'>
	<div id='block1'>
	<h1>Add Source Entries</h1>
	</div>

	<div id='block2'>
		<br><br>
		<form name="add" action="/$BATools::baCGI/sourceHandler">
		<br>
		<br>
		<h3>Distributions</h3>
		$dselect
		<br>
		<input class="button" type="submit" value="Add">
	</div>
	<div id='block3'>
		<br>
		<input class="sadd" type="checkbox"  name="iso" value="iso" onClick="enableISO(this)">
		<font class="sadd">Download ISO</font><br>
		<input class="sadd" type="text" name="user" value="username" disabled onFocus="clearText(this)">
		<input class="sadd" type="password" name="pass" value="password" disabled onFocus="clearText(this)">
		<br><br><br>
		<input class="sadd" type="checkbox" name="proxy" value="proxy" onClick="enableProxy(this)">
		<font class="sadd">Use Proxy</font><br>
		<input class="sadd" type="text" name="paddr" value="hostname" disabled onFocus="clearText(this)">
		<input class="sadd" type="text" name="puser" value="username" disabled onFocus="clearText(this)">
		<input class="sadd" type="password" name="ppass" value="password" disabled onFocus="clearText(this)">
	</div>
		<input type="hidden" name="sub" value="add">
		<input type="hidden" name="ref" value="yes">
		</form>

	<div id='status'>
	<textarea name="comments" class="tbox" readonly="yes">$help</textarea>
	</div>
	</div>
	<body>
	</html>

HTML0

########################################################################################################
#  Read Help File
########################################################################################################

sub print_help()
{
	my $retString = "";
	open (MYFILE, $source_help) || return "Error Opening Help File:\n$!";
	while(<MYFILE>)
	{
		$retString = $retString.$_;
	}
	close (MYFILE);
	return $retString; 
}	

