#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $targetid = "";
my $targetip = "";

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
		<link rel='stylesheet' href='/$BATools::baRoot/css/storage.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST">
		<div id='config'>
		<div id='histbar' style="color:black"><a href=\"http://blade9/baracus/ba/repo\">Storage<\/a> \ >  Create</div>
		<div id='main'>
                <font class='name'>Name</font>
		<input type='text' class='createname' name='repo' value='$targetid'>
                <font class='createip'>Target IP</font>
                <input type='text' class='createip' name='repo' value='$targetip'>
		<br><br>
                </div>
		</div>
                </div>
		</form>
	</body>
</html>
HTML0

;
