#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use lib '/usr/share/baracus/perl/';
use BATools qw(:standard);
use BaracusConfig qw( :vars );
use CGI qw(:standard);

my $targetid = param('targetid') || "";

my $detail = getdetail( $targetid );

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
                <script type="text/javascript" src="/baracus/script/tablecloth.js"></script>
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
                <link rel='stylesheet' href='/$BATools::baRoot/css/tablecloth.css' type='text/css'>
		<link rel='stylesheet' href='/$BATools::baRoot/css/repo.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST">
		<div id='config'>
		<div id='histbar' style="color:black">Storage</div>
                <div id='histbar' style="color:black"><a href=\"http://$baVar{serverip}/baracus/ba/storage\">Storage<\/a> \ >  $targetid</div>
		<div id='main'>
		<br><br>
                <div id='repolist'>
		$detail
                </div>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getdetail
{
    my $targetid = shift;
    my $r = "";

    my $hohref = BAdb::getStorageDetail( $targetid );

    $r .= "<b>IP Address:</b> $hohref->{'targetip'}<br>\n";
    $r .= "<b>Name:</b> $hohref->{'name'}<br>\n";
    $r .= "<b>Description:</b> $hohref->{'description'}<br>\n";
    $r .= "<b>Size:</b> $hohref->{'size'}<br>\n";
    $r .= "<b>Type:</b> $hohref->{'type'}<br>\n";

    return $r;	
}

;
