#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use lib '/usr/share/baracus/perl/';
use BATools qw(:standard);
use BaracusConfig qw( :vars );
use CGI qw(:standard);

my $name = param('repo') || "";
my $filterVal = param('filter') || "";

my $items = getItems( $name, $filterVal );

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
                <script type="text/javascript" src="/baracus/script/tablecloth.js"></script>
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
                <link rel='stylesheet' href='/$BATools::baRoot/css/tablecloth.css' type='text/css'>
		<link rel='stylesheet' href='/$BATools::baRoot/css/storage.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST">
		<div id='config'>
		<div id='histbar' style="color:black">Storage</div>
		<div id='main'>
		<img class='search' src='/$BATools::baRoot/images/searchI.gif' onClick='document.form1.submit()'/>
		<img class='sweep' src='/$BATools::baRoot/images/sweepI.gif' onClick='document.form1.filter.value="";document.form1.submit()'/>
                <font class='filter'>Filter</font>
		<input type='text' class='filter' name='filter' value='$filterVal'>
                <font class='clink'><a href="http://$baVar{serverip}/baracus/ba/storageCreate">Create Storage Entry</a></font>
		<br><br>
                <div id='list'>
		$items
                </div>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = shift;
	my $filterVal = shift;
	my $r = "";
        my $linkD = "http://$baVar{serverip}/baracus/ba/storageDetail?targetid=";
        my $linkR = "http://$baVar{serverip}/baracus/ba/storageRemove?targetid=";

        if ( $filterVal eq "" ) { $filterVal = "%"; }

        $r = "<table class='repolist'>\n";
	my $hohref = BAdb::getStorageListDb( $filterVal );

	foreach  my $row ( keys %{$hohref} ) {
	    $r = $r."<tr>\n";
            $r .= "<td width=\"225\">$hohref->{$row}->{'targetid'}<\/td>\n";
            $r .= "<td width=\"295\">$hohref->{$row}->{'name'}<\/td>\n";
            $r .= "<td width=\"35\"><a href=\"$linkD$hohref->{$row}->{'targetid'}\" style=\"text-decoration : none\">Detail<\/a><\/td>\n";
            $r .= "<td width=\"10\"><a href=\"$linkR$hohref->{$row}->{'targetid'}\" style=\"text-decoration : none\"><font color=\"red\">X</font><\/a><\/td>\n";
	    $r .= "<\/tr> \n";
	}	

	$r = $r."</table>\n";
	return $r;	
}

;
