#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use lib '/usr/share/baracus/perl/';
use BATools qw(:standard);
use BaracusConfig qw( :vars );
use CGI qw(:standard);

my $targetid = "";
my $targetip = "";
my $name = "";
my $size = "";
my $description = "";
my $username = "";
my $passwd = "";

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
		<link rel='stylesheet' href='/$BATools::baRoot/css/storage.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' action='storageHandler' method="POST">
		<div id='config'>
		<div id='histbar' style="color:black"><a href=\"http://$baVar{serverip}/baracus/ba/storage\">Storage<\/a> \ >  Create</div>
		<div id='main'>
                <font class='createname'>Target Name</font>
		<input type='text' class='createname' name='createname' value='$name'>
                <font class='createip'>Target IP</font>
                <input type='text' class='createip' name='targetip' value='$targetip'>
                <font class='createid'>Target ID</font>
                <input type='text' class='createid' name='targetid' value='$targetid'>
                <font class='createtype'>Target Type</font>
                <select class='createtype' name='type'>
                   <option value='iscsi'>ISCSI</option>
                   <option value='aoe'>AOE</option>
                   <option value='nfs'>NFS</option>
                </select>
                <font class='createsize'>Target Size</font>
                <input type='text' class='createsize' name='targetsize' value='$size'>
                <font class='createdesc'>Target Description</font>
                <input type='text' class='createdesc' name='targetdesc' value='$description'>
                <font class='createuser'>Username</font>
                <input type='text' class='createuser' name='username' value='$username'>
                <font class='createpasswd'>Password</font>
                <input type='text' class='createpasswd' name='passwd' value='$passwd'>
                <input type='submit' class='createentry' value='Create Entry'>
		<br><br>
                </div>
		</div>
                </div>
		</form>
	</body>
</html>
HTML0

;
