#!/usr/bin/perl

#use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);
#
my $content = getData();
#my $content = `perl /data/baracus/trunk/root/var/spool/baracus/www/modules/expect --distro=sles10-x86_64`;

my $cgi = new CGI;
print $cgi->header();
print 'user_agent(): ' . $cgi->user_agent() . '<br>';
print 'remote_host(): ' . $cgi->remote_host() . '<br>';
print 'script_name(): ' . $cgi->script_name() . '<br>';
print 'referer(): ' . $cgi->referer() . '<br>';
print 'request_method(): ' . $cgi->request_method() . '<br>'; 

sub getData()
{
	my $m1 = BAdb::getDistros("*");
	my $r = "";

	foreach( @$m1)
	{
		$r = $r.$_->[0]." ".$_->[1]."<br>";
	}
	return $r;
}
