#!/usr/bin/perl

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

#my $content = getData();
my $content = `perl /data/baracus/trunk/root/var/spool/baracus/www/modules/expect --distro=sles10-x86_64`;

print "Content-type: text/html\n\n";





print <<HTML;

<html>
<head>
	<link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >
</head>
<body> 
<br>
<br>
t e s t i n g
<br>
<br>
<hr>
$content
</body>
</html>

HTML
;


sub getData()
{
	BATools::execute("perl /data/baracus/trunk/root/var/spool/baracus/www/modules/expect/ba1 --distro=sles10-x86_64");
}
