#!/bin/bash

baconfig detail hardware default &> /dev/null || \
baconfig add hardware --name default \
--description="default" \
--bootargs="acpi=on selinux=0 apm=off" \
--rootdisk=/dev/sda \
--rootpart=/dev/sda \
--pxetemplate=pxetemplate-auto \
--yasttemplate=template.xml 
#--oscert=SLES9:SLES10
#--addon="<!--no addon -->"
#--hwdriver="<!--no hwdrivers -->"

baconfig detail hardware default-HP &> /dev/null || \
baconfig add hardware --name default-HP \
--description="default-HP" \
--bootargs="acpi=on selinux=0 apm=off" \
--rootdisk=/dev/cciss/c0d0 \
--rootpart=/dev/cciss/c0d0p \
--pxetemplate=pxetemplate-auto \
--yasttemplate=template.xml
#--oscert=SLES9:SLES10
#--addon="<!--no addon -->"
#--hwdriver="<!--no hwdrivers -->"

baconfig detail hardware kvm-sda &> /dev/null || \
baconfig add hardware --name kvm-sda \
--description="KVM (sda)" \
--bootargs="acpi=on selinux=0 apm=off" \
--rootdisk=/dev/sda \
--rootpart=/dev/sda \
--pxetemplate=pxetemplate-auto \
--yasttemplate=template.xml 
#--oscert=SLES9-64:SLES10-64:SLES11-64 \
#--addon="<!--no addon -->"
#--hwdriver="<!--no hwdrivers -->"

baconfig detail hardware kvm-hda &> /dev/null || \
baconfig add hardware --name kvm-hda \
--description="KVM (hda)" \
--bootargs="acpi=on selinux=0 apm=off" \
--rootdisk=/dev/hda \
--rootpart=/dev/hda \
--pxetemplate=pxetemplate-auto \
--yasttemplate=template.xml
#--oscert=SLES9-64:SLES10-64:SLES11-64
#--addon="<!--no addon -->"
#--hwdriver="<!--no hwdrivers -->"

