#!/usr/bin/perl -w

use strict;
use XML::Simple qw( :strict);

my $debug = 0;

my $xs = XML::Simple->new ( SuppressEmpty => 1,
                            ForceArray => [ qw (distro product iso) ],
                            KeyAttr => { distro => 'name',
                                         product => 'name',
                                         iso => 'name' },
                           );

my $ref = $xs->XMLin( "/usr/share/baracus/badistro.xml" );


# ####
# $xs->{'distro'}->{$dname}
# has keys:
#   os, release, arch
#   description
#   autodownload
#   ( and if no contained product is addon type base )
#   requires, addos, ( and maybe ) addrel

# ####
# $xs->{'distro'}->{$dname}->{'product'}->{$pname}
# has key 'addon' (values: base, flat, signed, yum)

# ####
# $xs->{'distro'}->{$dname}->{'product'}->{$pname}->{'iso'}->{$iname}
# has keys:
#   path, md5, url
#   ( and if addon eq 'base' for the product then also )
#   kernel, initrd

my $os;
my $release;
my $arch;
my $addon;
my $addos;
my $addrel;
my $builddistro;

foreach my $distro (keys %{$ref->{'distro'}} ) {
    $os = $ref->{'distro'}->{$distro}->{'os'};
    $release = $ref->{'distro'}->{$distro}->{'release'};
    $arch = $ref->{'distro'}->{$distro}->{'arch'};
    if ( defined $ref->{'distro'}->{$distro}->{'requires'} and
         $ref->{'distro'}->{$distro}->{'requires'} ) {
        # ignore requires content
#       $baseos = $ref->{'distro'}->{$distro}->{'requires'}; 
        $addos = $ref->{'distro'}->{$distro}->{'addos'};
        if (defined $ref->{'distro'}->{$distro}->{'addrel'}) {
            $addrel = $ref->{'distro'}->{$distro}->{'addrel'};
        } else {
            $addrel = "";
        }
        $addon = 1;
    } else {
        $addon = 0;
    }

    $builddistro = "$os-$release-";
    if ( $addon ) {
        $builddistro .= "$addos-";
        if ( $addrel ) {
            $builddistro .= "$addrel-";
        }
    }
    $builddistro .= "$arch";

    if ( $distro ne $builddistro ) {
        # we die here as this would otherwise be very difficult to track down
        die "SKIP MALFORMED XML ENTRY '$distro' ne '$builddistro'\n";
        # next;
    }

    if ($debug) {
        print "distro $distro\n";
        print "os $os release $release arch $arch\n";
        if ($addon) {
            print "addon os $addos and addon release $addrel\n";
        }
    }

    my $desc = $ref->{'distro'}->{$distro}->{'description'};

    my $cmd = "baconfig add distro ";
    $cmd .= " --os $os";
    $cmd .= " --release $release";
    $cmd .= " --arch $arch";
    $cmd .= " --description \"$desc\"";
    if ( $addon ) {
        $cmd .= " --addon --addos $addos";
        if ( $addrel ) {
            $cmd .= " --addrel $addrel";
        }
    }
    print $cmd . "\n" if $debug;
    my $retval = system("baconfig detail distro $os &> /dev/null");
    system ($cmd) if ($retval);
}

exit 0;

die "DOES NOT EXECUTE";

1;

__END__

