#!/usr/bin/perl -w

use strict;
use XML::Simple;

my $debug = 0;

my $xml = new XML::Simple;
my $config = $xml->XMLin( "/usr/share/baracus/qs.xml",
                          forcearray => [ 'distribution', 'file' ],
                          keyattr => [ 'distribution' => 'os' ]
                         );

my $addon;
my $baseos;
my $osnoarch;
my $arch;
my $sp;
my $desc;

foreach my $os (keys %{$config->{'distribution'}} ) {
    $arch = $config->{'distribution'}->{$os}->{'arch'};
    $osnoarch = $os;
    $osnoarch =~ s|\-$arch||;
    $sp = $config->{'distribution'}->{$os}->{'sp'};
    if ( $sp =~ m|[0-9]| ) {
        $sp = "sp$sp";
    }
    if (defined $config->{'distribution'}->{$os}->{'requires'}) {
        $addon = 1;
        $baseos = $config->{'distribution'}->{$os}->{'requires'};
        $baseos =~ s|\-$arch||;
    } else {
        $addon = 0;
    }
    print "os $os sp $sp\n" if $debug;
    $desc = $config->{'distribution'}->{$os}->{'description'};

    my $cmd = "baconfig add distro --name $os";
    $cmd .= " --os $osnoarch";
    $cmd .= " --arch $arch";
    $cmd .= " --sp $sp";
    $cmd .= " --description \"$desc\"";
    $cmd .= " --addon --baseos $baseos" if $addon;

    my $retval = system("baconfig detail distro $os &> /dev/null");
    system ($cmd) if ($retval);
}

exit 0;

die "DOES NOT EXECUTE";

1;

__END__

