.\" Process this file with
.\" groff -man -Tascii create_install_source.5
.\"
.TH CREATE_INSTALL_SOURCE 5 "MAY 2009" Linux "User Manuals"
.SH NAME
create_install_source \- command line tool for generating \- maintaining a build server
.SH SYNOPSIS
.B create_install_source command [options]
.SH COMMANDS
.IP 
    menu                          : run full menu mode 
    add     --distro <x>          : add a new build source for distribution <x>
    remove  --distro <x>          : remove <x> as a build source
    disable --distro <x>          : diable a build source for distribution <x>
    enable  --distro <x>          : enable a build source for distribution <x>
    list    --distro <x>          : list required isos for distribution <x>
    verify  --distro <x>          : verify build source for distribution <x>
    service < --start | --stop >  : start or stop the default services
    service --start y [--start y] : start specified service(s) (nfs,http,dhcpd)
    service --stop  y [--stop  y] : stop specified service(s) (nfs,http,dhcpd)

.SH OPTIONS
.IP 
    -i|--isos                     : 'add' option - download iso to directory 
    -p|--proxy                    : 'add' option - use proxy for iso downloads 
    -v|--verbose                  : verbose output 
    -h|--help                     : this (help) message


.SH AUTHOR
Dan Westervelt
.SH "SEE ALSO"
.BR Baracus (1),
.BR Baracus (5),
.BR create_install_host (5)

