#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

my $op = param('op') || "version";
my $current = "";

my @tmenu = ( "version", "basource", "baconfig", "bahost", "bado", "bapower", "balog");
my @tlink = ( "aboutVersion", "aboutBASource", "aboutBAConfig", "aboutBAHost", "aboutBADo", "aboutBAPower", "aboutBALog");

my $tabs = BATools::getTabs( \@tmenu, \@tlink, $op, "about");

print "Content-type: text/html\n\n";

print <<HTML;

<html>
<head>
	<link rel='stylesheet' href='/$BATools::baRoot/css/tabs.css' type='text/css' >
	<link rel='stylesheet' href='/$BATools::baRoot/css/about.css' type='text/css' >
</head>
<body>
<br>
<br>
$tabs
</body>
</html>

HTML
;


