#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $name = param('host') || "";
my $filterVal = param('filter') || "";
my $filterKey = param('filterKey') || "hostname";
my $ltype = param('ltype') || "nodes";
my $inv = param('inv') || "no";
my $invState = "disabled";

my $items = getItems( $name, $filterVal, $filterKey, $ltype);
my $content = "";
my $mac = "";

if( $items =~ m/selected/)
{
	$mac = (split(/ /, $name))[0];
	$content = getContent( $mac);
	if( hasInventory($mac) eq "yes")
	{
		$invState = "enabled";
	}
	
}

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<script type="text/javascript" src="/baracus/script/common.js"></script>
		<link rel='stylesheet' href='/$BATools::baRoot/css/host.css' type='text/css'>
		<script type="text/JavaScript">
		<!--
			function popResponse( name)
			{
				win = window.open("/baracus/ba/inventoryHandler?mac=" + name,
									"myWin",
									"");
				return true;
			}			
			
		//-->
		</script>		
	</head>
	<body onLoad='selectThis(document.form1.host, "$name");document.form1.host.focus();selectRadio(document.form1.filterKey, "$filterKey");selectRadio(document.form1.ltype, "$ltype")'>
		<form name='form1' method="POST">
		<div id='config'>
		<div id='history' style="color:black">Host Entry List</div>
		<div id='textEdit'>
		<div id='ltype'>
			<input class="radio" type="radio" name="ltype" value="nodes" checked onclick='document.form1.submit()'>Nodes
			<input class="radio" type="radio" name="ltype" value="templates" onclick='document.form1.submit()'>Templates
			<input class="radio" type="radio" name="ltype" value="states" onclick='document.form1.submit()'>States		
		</div>
		<div id='fkey'>
			Filter:  
			<input type="radio" name="filterKey" value="hostname" onclick='document.form1.submit()'>Hostname
			<input type="radio" name="filterKey" value="mac" checked onclick='document.form1.submit()'>Mac
		</div>
		<img class='search' src='/$BATools::baRoot/images/searchI.gif' onClick='document.form1.submit()'/>
		<img class='sweep' src='/$BATools::baRoot/images/sweepI.gif' onClick='document.form1.filter.value="";document.form1.submit()'/>
		<input type='text' class='filter' name='filter' value='$filterVal'>
		
		<input style="position:absolute;top:315px;left:470px;width:100px;disabled="$invState" name="inventory" type="button" value="Inventory" onClick='popResponse(\"$mac\")'>
		
		
		<font class='name'>Host Name</font><br>
		$items
		<br><br>
		<font class='dataShort'>Host Data</font>
		<textarea class='short' name='data' readonly>$content</textarea>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = $_[0];
	my $fVal = $_[1];
	my $fKey = $_[2];
	my $lType = $_[3];
	my $filter = "";
	if( $fVal ne "" && $fKey ne "")
	{
		$filter = "--filter $fKey\:\:$fVal";
	}
	else
	{
		$filter = "";
	}
	my $r = "";
	my $selected;

	my @items;
	if( $lType eq "templates")
	{
		$r = $r."<select class='nameWide' name='host' size='16' disabled>";
		@items = BAdb::getHostTemplates( $filter);
	}
	elsif( $lType eq "nodes")
	{
		$r = $r."<select class='nameWide' name='host' size='16' onChange='doSubmit( this)'>";
		@items = BAdb::getHostNodes( $filter);
	}
	elsif( $lType eq "states")
	{
		$r = $r."<select class='nameWide' name='host' size='16' disabled>";
		@items = BAdb::getHostStates( $filter);
	}
	else
	{
		$r = $r."<select class='nameWide' name='host' size='16'>";
	}

	foreach( @items)
	{
		$selected = $_ eq $name ? "selected" : "";
		$r = $r."<option value=\"$_\" $selected>$_</option>\n";	
	}
	
	$r = $r."</select>";
	
	return $r;	
}

sub getContent
{
    my $r;
	my $name = shift @_;
	if( $name eq "")
	{
	    $r = "";
	}
	else
	{
		$r = BAdb::getNodeDetail( $name);
	}
	return $r;
}

sub hasInventory
{
	my $mac = shift @_;
	return BAdb::getNodeInventory( $mac) ne "" ? "yes" : "no";
}
;
