#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use CGI qw(:standard);

my $name = param('host') || "";
my $filterVal = param('filter') || "";
my $filterKey = param('filterKey') || "hostname";
my $ltype = param('ltype') || "nodes";

my $items = getItems( $name, $filterVal, $filterKey, $ltype);
my $content;

if( $items =~ m/selected/)
{
	$content = getContent( $name);
}

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<script type="text/javascript" src="/baracus/script/common.js"></script>
		<link rel='stylesheet' href='/$BATools::baRoot/css/host.css' type='text/css' >
	</head>
	<body onLoad='selectThis(document.form1.host, "$name");document.form1.host.focus();selectRadio(document.form1.filterKey, "$filterKey");selectRadio(document.form1.ltype, "$ltype")'>
		<form name='form1' method="POST" action="/$BATools::baCGI/hostHandler">
		<div id='config'>
		<div id='history' style="color:black">Host Entry Remove</div>
		<div id='textEdit'>
		<div id='ltype'><br></div>
		<div id='fkey'>
			Filter:  
			<input type="radio" name="filterKey" value="hostname" onclick='hostReload( document.form1.host.value, this.value, document.form1.filter.value)'>Hostname
			<input type="radio" name="filterKey" value="mac" checked onclick='hostReload( document.form1.host.value, this.value, document.form1.filter.value)'>Mac
		</div>

		<img class='search' src='/$BATools::baRoot/images/searchI.gif' onClick='hostReload( document.form1.host.value, "$filterKey", document.form1.filter.value)'/>
		<img class='sweep' src='/$BATools::baRoot/images/sweepI.gif' onClick='document.form1.filter.value="";hostReload( document.form1.host.value, "$filterKey", document.form1.filter.value);'/>
		<input type='text' class='filter' name='filter' value='$filterVal' onKeyPress='return hostRemoveEnterKey(event, "$filterKey")'>
		
		<input type="hidden" name="sub" value="del">
		<input style="position:absolute;top:315px;left:470px;width:100px" name="submit" type="submit" value="Remove" onClick='return verifyDelete( this.form.host.value)'>
		
		<font class='name'>Host Name</font><br>
		$items
		<br><br>
		<font class='dataShort'>Host Data</font>
		<textarea class='short' name='data' readonly>$content</textarea>
		</div>
		</div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = $_[0];
	my $fVal = $_[1];
	my $fKey = $_[2];
	my $lType = $_[3];
	my $ filter = "";
	if( $fVal ne "" && $fKey ne "")
	{
		$filter = "--filter $fKey\:\:$fVal";
	}
	else
	{
		$filter = "";
	}
	my $r = "";
	my $selected;
	
	
	my @items;

	$r = $r."<select class='nameWide' name='host' size='16' onChange='hostReload( document.form1.host.value, \"$filterKey\", document.form1.filter.value);'>";
	@items = BAdb::getHostNodes( $filter);

	foreach( @items)
	{
		$selected = $_ eq $name ? "selected" : "";
		$r = $r."<option value=\"$_\" $selected>$_</option>\n";	
	}
	
	$r = $r."</select>";
	
	return $r;	
}

sub getContent
{
	my $name = $_[0];
	if( $name eq "")
	{
		$r = "";
	}
	else
	{
		my $mac = (split(/ /, $name))[0];
		$r = BAdb::getNodeDetail( $mac);
	}
	return $r;
}

