#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use strict;
use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);
use vars qw( %hash @array);
use CGI qw(:standard);

print "Content-type: text/html\n\n";

our $menuindex = 0;
our @menucmd;
our @menunames;

my $cmd;
my $data_file;
my $result;
my $request;
my $op;
my $data;
my $menuHTML;
my $randImage;
my $content;

$op = param('op') || '<i>(No input)</i>';
$data = param('data');

@menunames = ( "Host Entries",
	       "Host Boot Action",
               "Source Entries",
               "Configuration",
               "Power Controller",
               "Repository",
               "Storage",
               "Log Information",
               "Processing",
               "About" );

@menucmd = ( "/$BATools::baCGI/host.iframe",
             "/$BATools::baCGI/action.iframe",
             "/$BATools::baCGI/source.iframe",
             "/$BATools::baCGI/config.iframe",
             "/$BATools::baCGI/power.iframe",
             "/$BATools::baCGI/repo.iframe",
             "/$BATools::baCGI/storage.iframe",
             "/$BATools::baCGI/log.iframe",             
             "/$BATools::baCGI/procHandler.iframe",
             "/$BATools::baCGI/about.iframe" );

$menuHTML = createMenu( $op );
$content = processCommand( $data );

########################################################################################################
#  Print HTML
########################################################################################################

print <<HTML1;

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<link rel='stylesheet' href='/$BATools::baRoot/css/common.css' type='text/css' >
		<link rel='stylesheet' href='/$BATools::baRoot/css/forms.css' type='text/css' >
		<link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >
		<script type="text/javascript" src="/$BATools::baRoot/script/common.js"></script>
		<title>Baracus</title>
	</head>
	
	<body bgcolor="gainsboro" onClick="parent_disable();">
        <div id='mextend'>&nbsp;&nbsp;&nbsp;<img src="/baracus/images/baracuslogo1.gif" height="35" \></div>
	<div id='mmenu'>
	$menuHTML
	</div>
	<div id='content'>
	$content
	</div>
	<div id="nvlogo"><a href="http://www.novell.com"><img src="/$BATools::baRoot/images/nov_blk.gif"\></a></div> 
	</body>
</html>

HTML1


########################################################################################################
#  Generate Menu From menunames / Highlight current selection
########################################################################################################

sub createMenu
{
	my $retString = "";
	my $divid = "";
	my $curop = $_[0];
	my $iter = 0;

	$menuindex = 0;
	
	foreach (@menunames)
	{
		if($_ eq $curop)
		{
			$divid = "cur";
			$menuindex = $iter;
		}
		
		$retString = $retString."<a href='/$BATools::baCGI/main?op=$_'><div id='$divid'>&nbsp;&nbsp;&nbsp;$_</div></a>\n";
		
		$divid = "";
		++ $iter;
	}

	return $retString;	
}	

########################################################################################################
#  Execute Command or include file if command ends with "html"
########################################################################################################

sub processCommand
{
	my $data = $_[0];
	my $retString = "";
	my $result;
	
	####################################################################################################
	#Menu Command maps to @menunames.
	#.html - puts html file inline (head and body tags should NOT be present in html file)
	#.iframe - strips .iframe from command and loads stripped command in iframe
	#All others are treated as executables - results displayed
	####################################################################################################

	$cmd = $menucmd[$menuindex];
	 
	if($data ne "")
	{
		$retString = $data;
	}
	elsif ($cmd =~ m/html\Z/)
	{
		$data_file="$BATools::baPath/htdocs/" . $cmd;
		open(DAT, $data_file) || print "Could not open file: " . $data_file;
		while(<DAT>)
		{
			$retString = $retString.$_;
		}
		close(DAT); 				
	}
	elsif ($cmd =~ m/iframe\Z/)
	{
		$cmd =~ s/.iframe//;
		if( $cmd =~ m/html\Z/)
		{
			$data_file="$BATools::baPath/htdocs/" . $cmd;
			open(DAT, $data_file) || print "Could not open file: " . $data_file;
			while(<DAT>)
			{
				$retString = $retString.$_;
			}
			close(DAT);
		}
		else
		{
			$retString = "\t<iframe frameborder='0' scrolling='no' src='$cmd' name='createframe'></iframe>\n";
		}
	}
	else
	{
		$result = `$cmd`;
		
		if ( $cmd !~ m/\Aperl/)
		{
			$result = "<ul>\n".$result;
			#Add <br> for each new line in $result
			$result=~s/\n/<br>\n\t<li>/g;
			$result = $result."</ul>\n";
		}
		
		$retString = "\t<div id='pcontent'>";
		$retString = $retString.$result;
		$retString = $retString."\t</div>\n";
	}
	
		return $retString;
}	
