#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use strict;
use lib '/var/spool/baracus/www/modules';
use lib '/usr/share/baracus/perl/';
use BATools qw(:standard);
use BaracusConfig qw( :vars );
use CGI qw(:standard);

my $mac = "";
my $hostname = "";
my $bmcaddr = "";
my $type = "";
my $username = "";
my $passwd = "";

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
		<link rel='stylesheet' href='/$BATools::baRoot/css/power.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST" action="powerHandler">
		<div id='config'>
		<div id='histbar' style="color:black"><a href=\"http://$baVar{serverip}/baracus/ba/power\">Power<\/a> \ >  Create</div>
		<div id='main'>
                <font class='createname'>mac</font>
		<input type='text' class='createname' name='mac' value='$mac'>
                <font class='createip'>hostname</font>
                <input type='text' class='createip' name='hostname' value='$hostname'>
                <font class='createid'>BMC address</font>
                <input type='text' class='createid' name='bmcaddr' value='$bmcaddr'>
                <font class='createtype'>BMC Type</font>
                <select class='createtype' name='type'>
                   <option value='ipmi'>IPMI</option>
                   <option value='ilo'>ILO</option>
                   <option value='drac'>DRAC</option>
                   <option value='racs'>RACS</option>
                   <option value='bladecenter'>BLADECENTER</option>
                   <option value='apc'>APC</option>
                   <option value='virsh'>VIRSH</option>
                </select>
                <font class='createuser'>Username</font>
                <input type='text' class='createuser' name='username' value='$username'>
                <font class='createpasswd'>Password</font>
                <input type='text' class='createpasswd' name='passwd' value='$passwd'>
                <input type='submit' class='createentry' value='Add' name='submit'>
		<br><br>
                </div>
		</div>
                </div>
		</form>
	</body>
</html>
HTML0

;
