#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use strict;
use lib '/var/spool/baracus/www/modules';
use lib '/usr/share/baracus/perl/';
use BATools qw(:standard);
use BaracusConfig qw( :vars );
use CGI qw(:standard);

my $repo = param('repo') || "";

my $items = getItems( $repo );

print "Content-type: text/html\n\n";
	
print <<HTML0

<html>
	<head>
		<META HTTP-EQUIV="Expires" CONTENT="Tue, 04 Dec 1993 21:29:02 GMT">
                <script type="text/javascript" src="/baracus/script/tablecloth.js"></script>
		<script type="text/javascript" src="/baracus/script/common.js"></script>
                <link rel='stylesheet' href='/baracus/css/tabs.css' type='text/css' >  
                <link rel='stylesheet' href='/$BATools::baRoot/css/tablecloth.css' type='text/css'>
		<link rel='stylesheet' href='/$BATools::baRoot/css/repo.css' type='text/css'>
	</head>

	<body>
                <br>
                <br>
                <div class='menu'>
                <ul></ul>
                </div>

		<form name='form1' method="POST">
		<div id='config'>
		<div id='histbar' style="color:black"><a href=\"http://$baVar{serverip}/baracus/ba/repo\">Repository<\/a> \ >  $repo</div>
		<div id='main'>
                <font class='name'>RPM List</font>
		<br><br>
                <div id='repolist'>
		$items
                </div>
                <div id='addlink'><a href=\"http://$baVar{serverip}/baracus/ba/repoAdd?op=Add&&repo=$repo\">Add RPM<\/a></div>
		</div>
                </div>
		</form>
	</body>
</html>
HTML0
;

sub getItems
{
	my $name = $_[0];
	my $r = "";
	my $selected;
        my $linkR = "http://$baVar{serverip}/baracus/ba/repoRemove?repo=test&rpm=";

	my @items;
        $r = "<div class='tablediv'>";
        $r .= "<table class='repolist'>\n";
	@items = BAdb::getRepoDetail( $repo );

	foreach( @items)
	{
            $r .= "<tr>\n<td width=\"530\">$_<\/td>\n<td width=\"20\"><a href=\"$linkR$_\" style=\"text-decoration : none\">Remove<\/a><\/td>\n<\/tr> \n";
	}
	
	$r .= "</table>\n";
        $r .= "</div>\n";
	return $r;	
}

;
