#!/usr/bin/perl

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

use Config;
use Thread;

print "Content-type: text/html\n\n";

print "Start\n";


if ($Config{usethreads})
{ 
    print "We have threads\n"; 
} else
{ 
	print "We do NOT have threads\n";
}

$thr = new Thread \&sub1;

print "Waiting For Thread\n";

#$x = 0;
#while ($thr->is_running())
#{
#	++ $x;
#	@list = threads->list(threads::running);
#	print "..\n";
#	sleep 1;
#}


$thr->join;

print "All Done\n";


sub sub1
{
	
	open (MYFILE, '> data.txt') || die "Cannot open file: $!";
	print MYFILE "Data File Created\n\n";
	close (MYFILE); 

	$count = 0;
	while ($count < 6)
	{
		++ $count;
		open (MYFILE, '>> data.txt') || die "Cannot open file: $!";
		print MYFILE "In Thread: $count\n";
		close (MYFILE); 
		sleep 1;
	}
}
    
  
