#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);

my $filePath = "/$BATools::baPath/htdocs/pool/";
my $op = $ARGV[0];
my $distro = $ARGV[1];
my $addon = $ARGV[2];
my $verbose = $ARGV[3];
my $fileName = $filePath.$ARGV[4];
my $date = `date`;

if( $verbose ne "-v")
{
	$verbose = "";
}

if( $addon ne "NOADDON")
{
		$addon = "--addon $addon";
}
else
{
	$addon = "";
}

my $cmd = "sudo basource $op --distro $distro $addon 2>&1"; 

chomp($date);
open (NEWFILE, ">$fileName") || die "Error: $!";
print NEWFILE "$op $distro $addon ----- $date\n\n";
close (NEWFILE);


open(PS, "$cmd |") || die "Failed: $!\n";

while ( <PS> )
{
	open (NEWFILE, ">>$fileName") || die "Error: $!";
	print NEWFILE $_;
	close (NEWFILE);
}

open (NEWFILE, ">>$fileName") || die "Error: $!";
print NEWFILE "\n\nFINISHED\n\n";
close (NEWFILE);

sleep 60;
unlink($fileName);

