#!/usr/bin/perl

use lib '/var/spool/baracus/www/modules';
use BATools qw(:standard);

my $filePath = "/$BATools::baPath/htdocs/pool/";
my $op = $ARGV[0];
my $distro = $ARGV[1];
my $verbose = $ARGV[2];
my $fileName = $filePath.$ARGV[3];
my $date = `date`;

if( $verbose ne "-v")
{
	$verbose = "";
}

my $cmd = "sudo create_install_source $op --distro $distro 2>&1"; 

chomp($date);
open (NEWFILE, ">$fileName") || die "Error: $!";
print NEWFILE "$op $distro ----- $date\n$cmd\n\n";
close (NEWFILE);


open(PS, "$cmd |") || die "Failed: $!\n";

while ( <PS> )
{
	open (NEWFILE, ">>$fileName") || die "Error: $!";
	print NEWFILE $_;
	close (NEWFILE);
}

open (NEWFILE, ">>$fileName") || die "Error: $!";
print NEWFILE "\n\nFINISHED\n\n";
close (NEWFILE);

sleep 10;
#unlink($fileName);

