#!/bin/bash

###########################################################################
# 
# Baracus build and boot management framework
# 
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
# 
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
# 
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

# baconfig detail autobuild __name__ &> /dev/null || \
# baconfig add autobuild --name __name__ \
# --description="__desc__" \
# --file=/usr/share/baracus/templates/autobuild/__file__ \
# --cert=__distro__

# DHCP enabled autobuild templates
#
baconfig detail autobuild sles-10-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name sles-10-x86_64-dhcp \
--description="sles 10.x 64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/sles-10-x86_64-dhcp.xml \
--cert="sles-10.3-x86_64 sles-10.2-x86_64"

baconfig detail autobuild sles-11-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name sles-11-x86_64-dhcp \
--description="sles 11/11.1 64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/sles-11-x86_64-dhcp.xml \
--cert="sles-11-x86_64 sles-11.1-x86_64"

baconfig detail autobuild sles-11.1-ha-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name sles-11.1-ha-x86_64-dhcp \
--description="sles 11.1 HA 64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/sles-11.1-ha-x86_64-dhcp.xml \
--cert="sles-11.1-x86_64"

baconfig detail autobuild sles-11.1-x86_64-nfs  &> /dev/null || \
baconfig add autobuild --name sles-11.1-x86_64-nfs \
--description="sles 11/11.1 64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/sles-11.1-x86_64-nfs.xml \
--cert="sles-11-x86_64 sles-11.1-x86_64"

baconfig detail autobuild opensuse-11-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name opensuse-11-x86_64-dhcp \
--description="opensuse 11.x64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/opensuse-11-x86_64-dhcp.xml \
--cert="opensuse-11.1-x86_64 opensuse-11.2-x86_64 opensuse-11.3-x86_64"

baconfig detail autobuild rhel-http-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name rhel-http-x86_64-dhcp \
--description="rhel 5.x 64bit HTTP (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/rhel-http-x86_64-dhcp \
--cert="rhel-5.3-x86_64 rhel-5.4-x86_64 rhel-5.5-x86_64"

baconfig detail autobuild rhel-6.0-http-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name rhel-6.0-http-x86_64-dhcp \
--description="rhel 6.x 64bit HTTP (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/rhel-6.0-http-x86_64-dhcp \
--cert="rhel-6.0-x86_64"

baconfig detail autobuild esx-http-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name esx-http-x86_64-dhcp \
--description="ESX 4 64bit HTTP (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/esx-http-4.0-x86_64-dhcp \
--cert="esx-4.0-x86_64"

baconfig detail autobuild rhel-nfs-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name rhel-nfs-x86_64-dhcp \
--description="rhel 5.x 64bit NFS (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/rhel-nfs-x86_64-dhcp \
--cert="rhel-5.3-x86_64 rhel-5.4-x86_64 rhel-5.5-x86_64"

baconfig detail autobuild rhel-6.0-nfs-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name rhel-6.0-nfs-x86_64-dhcp \
--description="rhel 6.x 64bit NFS (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/rhel-6.0-nfs-x86_64-dhcp \
--cert="rhel-6.0-x86_64"

baconfig detail autobuild fedora-http-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name fedora-http-x86_64-dhcp \
--description="fedora 11/12/13 64bit HTTP (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/fedora-http-x86_64-dhcp \
--cert="fedora-11-x86_64 fedora-12-x86_64 fedora-13-x86_64"

baconfig detail autobuild fedora-nfs-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name fedora-nfs-x86_64-dhcp \
--description="fedora 11/12/13 64bit NFS (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/fedora-nfs-x86_64-dhcp \
--cert="fedora-11-x86_64 fedora-12-x86_64 fedora-13-x86_64"

baconfig detail autobuild fedora-14-http-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name fedora-14-http-x86_64-dhcp \
--description="fedora 14 64bit HTTP (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/fedora-14-http-x86_64-dhcp \
--cert="fedora-14-x86_64"

baconfig detail autobuild fedora-14-nfs-x86_64-dhcp  &> /dev/null || \
baconfig add autobuild --name fedora-14-nfs-x86_64-dhcp \
--description="fedora 14 64bit NFS (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/fedora-14-nfs-x86_64-dhcp \
--cert="fedora-14-x86_64"

baconfig detail autobuild ubuntu-x86_64-dhcp &> /dev/null || \
baconfig add autobuild --name ubuntu-x86_64-dhcp \
--description="ubuntu 9.10/10.4 64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/ubuntu-x86_64-dhcp \
--cert="ubuntu-9.10-x86_64 ubuntu-10.4-x86_64 ubuntu_desktop-10.4-x86_64"

baconfig detail autobuild debian-x86_64-dhcp &> /dev/null || \
baconfig add autobuild --name debian-x86_64-dhcp \
--description="debian 64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/debian-5.0.6-x86_64-dhcp \
--cert="debian-5.0.6-x86_64"

baconfig detail autobuild win_ent-7-x86_64-dhcp &> /dev/null || \
baconfig add autobuild --name win_ent-7-x86_64-dhcp \
--description="windows 64bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/win_ent-7-x86_64.xml \
--cert="windows_ent-7-x86_64 windows_server-2008-x86_64"

baconfig detail autobuild win_ent-x86-dhcp &> /dev/null || \
baconfig add autobuild --name win_ent-x86-dhcp \
--description="win enterprise 32bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/win_ent-7-x86.xml \
--cert="windows_ent-7-x86"

baconfig detail autobuild xenserver-5.6.0-x86-dhcp  &> /dev/null || \
baconfig add autobuild --name xenserver-5.6.0-x86-dhcp \
--description="xenserver 5.6.0 32bit (dhcp)" \
--file=/usr/share/baracus/templates/autobuild/xenserver-5.6-x86-dhcp.xml \
--cert="xenserver-5.6.0-x86"

baconfig detail autobuild solaris-10.8-profile  &> /dev/null || \
baconfig add autobuild --name solaris-10.8-profile \
--description="solaris 10.8 64bit" \
--file=/usr/share/baracus/templates/autobuild/solaris-10.8-profile \
--cert="solaris-10.8-x86_64"

## Static autobuild templates
##
baconfig detail autobuild rhel-http-x86_64 &> /dev/null || \
baconfig add autobuild --name rhel-http-x86_64 \
--description="rhel http 64bit (static ip)" \
--file=/usr/share/baracus/templates/autobuild/rhel-http-x86_64 \
--cert="rhel-5.5-x86_64 rhel-5.4-x86_64"

baconfig detail autobuild rhel-nfs-x86_64 &> /dev/null || \
baconfig add autobuild --name rhel-nfs-x86_64 \
--description="rhel nfs 64bit (static ip)" \
--file=/usr/share/baracus/templates/autobuild/rhel-nfs-x86_64 \
--cert="rhel-5.5-x86_64 rhel-5.4-x86_64"

baconfig detail autobuild slert-10.2-x86_64 &> /dev/null || \
baconfig add autobuild --name slert-10.2-x86_64 \
--description="sles 10.2 real-time 64bit (static ip)" \
--file=/usr/share/baracus/templates/autobuild/sles-10.2-rt-x86_64.xml \
--cert="sles-10.3-x86_64 sles-10.2-x86_64"

baconfig detail autobuild sles-10.2-x86_64-bnx2x &> /dev/null || \
baconfig add autobuild --name sles-10.2-x86_64-bnx2x \
--description="sles 10.2 64bit bnx2x update (static ip)" \
--file=/usr/share/baracus/templates/autobuild/sles-10.2-x86_64_bnx2x-chroot.xml \
--cert="sles-10.3-x86_64 sles-10.2-x86_64"

baconfig detail autobuild sles-11.1-x86_64 &> /dev/null || \
baconfig add autobuild --name sles-11.1-x86_64 \
--description="sles 11.1 64bit (static ip)" \
--file=/usr/share/baracus/templates/autobuild/sles-11.1-x86_64.xml \
--cert="sles-11.1-x86_64 sles-11-x86_64"

baconfig detail autobuild sles-11.1-s390x &> /dev/null || \
baconfig add autobuild --name sles-11.1-s390x \
--description="sles 11.1 S390 64bit (static ip)" \
--file=/usr/share/baracus/templates/autobuild/sles-11.1-s390x.xml \
--cert="sles-11.1-s390x sles-10.3-s390x"

baconfig detail autobuild ubuntu-10.4-x86_64 &> /dev/null || \
baconfig add autobuild --name ubuntu-10.4-x86_64 \
--description="ubuntu 10.4 64bit (static ip)" \
--file=/usr/share/baracus/templates/autobuild/ubuntu-x86_64 \
--cert="ubuntu-10.4-x86_64 ubuntu_desktop-10.4-x86_64 ubuntu-9.10-x86_64"

