#!/bin/bash

###########################################################################
#
# Baracus build and boot management framework
#
# Copyright (C) 2010 Novell, Inc, 404 Wyman Street, Waltham, MA 02451, USA.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the Artistic License 2.0, as published
# by the Perl Foundation, or the GNU General Public License 2.0
# as published by the Free Software Foundation; your choice.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Both the Artistic
# Licesnse and the GPL License referenced have clauses with more details.
#
# You should have received a copy of the licenses mentioned
# along with this program; if not, write to:
#
# FSF, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110, USA.
# The Perl Foundation, 6832 Mulderstraat, Grand Ledge, MI 48837, USA.
#
###########################################################################

BUILD=psoagent2.1_vmbuild_sle11
HOST=psoagent2.1_vmhost_sle11

baconfig add module --name $BUILD --file $PWD/module/$BUILD    --desc "PSO 2.1 VM build host for SLE11"
baconfig add module --name $HOST  --file $PWD/module/$HOST     --desc "PSO 2.1 VM job host for SLE11"
baconfig add module --name reboot --file $PWD/module/reboot.sh --desc "reboot host (specify last in chain)"
